// richmonddata.js — Olney H. Richmond, Mystic Test Book (1893, public domain).
// Per-card data for the "Olney view" in mysticscards.html.
//
// • solar/spirit/astral: from Richmond's delineation table.
// • spread: his engraved "Grand Spread" plate for that card, transcribed from
//   the original scans. These are EMPIRICAL timed-shuffle lay-outs (Richmond's own
//   magnetism), NOT the site's deterministic solar quadration — so they cannot be
//   regenerated by deckAtAge(); each is hand-verified to a full 52-card deck.
//   sun = the 3 sun-line cards; lines = the 7×7 grid by planet row (each 7 cards,
//   left→right as printed); emblem = the card drawn on the plate as the O.O.M.
//   sunburst — always the Ace of Spades (present in the layout, not missing).
// • planets: Richmond's planet-by-planet delineation text (added incrementally).
//
// key = `${rank}_${suit}` (matches CARDS / LIFE_SCRIPTS).
window.RICHMOND = {
  "A_hearts": { name: "Ace of Hearts", solar: 1, spirit: 10, astral: "44722",
    spread: {
      sun: ["J♦","A♥","5♣"],
      lines: {
        Mercury: ["3♥","Q♦","K♠","10♣","K♥","8♦","10♠"],
        Venus: ["6♦","9♥","3♠","A♠","K♦","Q♣","7♦"],
        Mars: ["10♥","4♠","2♦","9♠","6♣","4♥","3♦"],
        Jupiter: ["A♦","J♣","Q♥","7♣","5♥","4♦","2♣"],
        Saturn: ["Q♠","6♥","9♦","8♣","A♣","J♥","5♠"],
        Uranus: ["7♥","10♦","K♣","2♥","J♠","6♠","9♣"],
        Neptune: ["8♥","8♠","7♠","5♦","3♣","2♠","4♣"]
      },
      emblem: "A♠ (Venus line, seat 4)"
    },
    planets: {
      Mercury: "A wish for warm love. Longing for affection from opposite sex. News from a friend near at hand. A telegram or telephone message.",
      Venus: "A love letter. A letter of friendship. Invitation to a party. Proposal of marriage by letter. A wish for love, friendship and affection. A desire for harmony.",
      Mars: "A wish to be of help to a friend. News of a friend in trouble. Desire to stand well with some person of strong mind and disposition.",
      Jupiter: "Desire for money an unselfish use. Wish to help for friends pecuniarily. Letter from a friend regarding some pecuniary favor. A telegram regarding money.",
      Saturn: "Wish to help some friend in sickness. Desire to aid the afflicted. News of the sickness of a friend. Letter announcing the death of a friend.",
      Uranus: "Wish to obtain employment of a friendly person. Strong wish regarding labor of some kind. Wish for and love of the occult.",
      Neptune: "Wish to go upon a journey of friendship. Longing to travel with a friend. Love of the unseen things of nature. Longing for message from a distance."
    } },
  "2_hearts": { name: "Two of Hearts", solar: 2, spirit: 20, astral: "36623",
    spread: {
      sun: ["K♠","2♥","6♣"],
      lines: {
        Mercury: ["4♥","8♦","A♦","J♣","9♥","K♦","Q♦"],
        Venus: ["7♦","10♥","4♠","2♠","9♦","8♣","9♠"],
        Mars: ["J♥","5♠","3♦","Q♣","7♣","5♥","4♦"],
        Jupiter: ["2♦","Q♠","8♥","8♠","6♥","5♦","3♣"],
        Saturn: ["A♣","7♥","10♦","K♣","2♣","J♠","6♠"],
        Uranus: ["A♠","J♦","9♣","3♥","A♥","7♠","10♣"],
        Neptune: ["K♥","Q♥","10♠","6♦","4♣","3♠","5♣"]
      },
      emblem: "A♠ (Uranus line, seat 1)"
    },
    planets: {
      Mercury: "A sudden passion for one of the opposite sex. Meeting an old friend unexpectedly. A friendly offer or proposal. Invitation to a party.",
      Venus: "Meeting of dear friends or lovers. Q h, 2h, Jh indicate an engagement of marriage. 8h a wedding. A union of hearts.",
      Mars: "Meeting of lovers, followed by a coolness or quarrel. Soon ended, however, and all is serene. Followed by a Jack, indicating a visit from a male friend.",
      Jupiter: "Two old friends meet. A happy visit soon ended. 2 h, Qh visit from a lady. If a King or Knave a visit from a gentleman.",
      Saturn: "Visit to a sick friend. If 7 s, 9 s, 2 h a meeting at a funeral. 2h, 8 c influence from an unseen friend. Followed by an ace, a letter from a friend who is ill.",
      Uranus: "Co-partnership in labor. Union in labor. Work with a friend. Engagement to labor. A bargain between two persons. With ace of hearts, a letter regarding work.",
      Neptune: "Meeting of friends after a long journey. Letter from a distance. 2h, Jh a love letter. Between J-J young men or sailors meet."
    } },
  "3_hearts": { name: "Three of Hearts", solar: 3, spirit: 30, astral: "15645",
    spread: {
      sun: ["A♦","3♥","7♣"],
      lines: {
        Mercury: ["5♥","K♦","2♦","Q♠","10♥","9♦","8♦"],
        Venus: ["9♠","J♥","5♠","3♠","10♦","K♣","Q♣"],
        Mars: ["J♠","6♠","4♦","8♣","8♠","6♥","5♦"],
        Jupiter: ["3♦","A♣","K♥","Q♥","7♥","6♦","4♣"],
        Saturn: ["2♣","A♠","J♦","9♣","3♣","A♥","7♠"],
        Uranus: ["2♠","K♠","10♣","4♥","2♥","10♠","J♣"],
        Neptune: ["9♥","8♥","Q♦","7♦","5♣","4♠","6♣"]
      },
      emblem: "A♠ (Saturn line, seat 2)"
    },
    planets: {
      Mercury: "Indecision of mind regarding love or matrimony. Two lovers at one time. Perplexity regarding your friends. Indecision regarding a visit.",
      Venus: "Two lovers at once. Indecision regarding love. Indecision as to attending a place of amusement or instruction. Perplexity of the heart.",
      Mars: "A proposal of marriage perplexes. Trouble to make up your mind. Two friends quarrel regarding something connected with yourself.",
      Jupiter: "Perplexity regarding a money matter connected with one you esteem or love. Two ways open at once. Help to a friend, regretted afterwards.",
      Saturn: "Trouble and concern, worry and indecision, caused by illness of self or friends. Wish to leave home but can not do so.",
      Uranus: "Trouble and perplexity with work. Two jobs pressing at once. Two roads open to you and you know not which to take.",
      Neptune: "Indecision relative to a journey. Wish to be in two places at once. Perplexing trouble at a distance. Followed by a. Jack, a man you trust causes it."
    } },
  "4_hearts": { name: "Four of Hearts", solar: 4, spirit: 40, astral: "54526",
    spread: {
      sun: ["2♦","4♥","8♠"],
      lines: {
        Mercury: ["6♥","9♦","3♦","A♣","J♥","10♦","K♦"],
        Venus: ["Q♣","J♠","6♠","4♠","J♦","9♣","8♣"],
        Mars: ["A♥","7♠","5♦","K♣","Q♥","7♥","6♦"],
        Jupiter: ["4♦","2♣","9♥","8♥","A♠","7♦","5♣"],
        Saturn: ["3♣","2♠","K♠","10♣","4♣","2♥","10♠"],
        Uranus: ["3♠","A♦","J♣","5♥","3♥","Q♦","Q♠"],
        Neptune: ["10♥","K♥","8♦","9♠","6♣","5♠","7♣"]
      },
      emblem: "A♠ (Jupiter line, seat 5)"
    },
    planets: {
      Mercury: "Satisfaction and success in love. Pleasure in making new friends. Sudden and unexpected happiness. Pleasure and happiness at home.",
      Venus: "Contentment with friendship and love. Satisfaction in love and a happy home. 4h, 8 c, 10 h satisfaction and success in unseen friends and influences.",
      Mars: "Satisfaction in friendly conversation with person of same sex. Satisfaction gained through law, if law-suit is shown elsewhere.",
      Jupiter: "Satisfaction in costly furniture. In fine dresses and a fine home. Love of fine surroundings. 10 h, 4h a love for your new work. 4h, 10 d pleasure in money making.",
      Saturn: "Recovery from illness by self or friends. Satisfaction with visits of unseen friends. Pleasure derived from kindness to the sick.",
      Uranus: "Satisfaction in your employment. Kindness of a friend regarding labor of some kind. Happiness in working for others.",
      Neptune: "Satisfaction in travel by water and land. Good lack in fishing or anything connected with the water. A visit of pleasant friends from afar."
    } },
  "5_hearts": { name: "Five of Hearts", solar: 5, spirit: 50, astral: "32333",
    spread: {
      sun: ["3♦","5♥","Q♥"],
      lines: {
        Mercury: ["7♥","10♦","4♦","2♣","J♠","J♦","9♦"],
        Venus: ["8♣","A♥","7♠","5♠","K♠","10♣","K♣"],
        Mars: ["2♥","10♠","6♦","9♣","8♥","A♠","7♦"],
        Jupiter: ["5♦","3♣","10♥","K♥","2♠","9♠","6♣"],
        Saturn: ["4♣","3♠","A♦","J♣","5♣","3♥","Q♦"],
        Uranus: ["4♠","2♦","Q♠","6♥","4♥","8♦","A♣"],
        Neptune: ["J♥","9♥","K♦","Q♣","7♣","6♠","8♠"]
      },
      emblem: "A♠ (Mars line, seat 6)"
    },
    planets: {
      Mercury: "Sudden change in life. Change in feelings. Removal of home somewhat unexpected. Short journey to home of friends.",
      Venus: "Change in love or friendship. Parting from friends. Journey to another city or town, K h, 5 h, Qh divorce or separation.",
      Mars: "Parting from male friends. A journey with a male. Removal for reasons connected with some man. Change of feelings towards a man.",
      Jupiter: "A business journey. Change in circumstances of a friend or a near relative. 5 h, 1 c, 2 c news of a change comes by letter.",
      Saturn: "Change of surroundings caused by sickness of friends. 7 s, 9 s, 5 h death is the cause of the change. Journey caused by ill health.",
      Uranus: "Journey by land. Change of residence. Removal of home and business. Visit of friends from a distance. With an ace, a letter.",
      Neptune: "Journey by water. Change of home or removal to a place near a body of water. A change connected with transportation and travel."
    } },
  "6_hearts": { name: "Six of Hearts", solar: 6, spirit: 60, astral: "43593",
    spread: {
      sun: ["4♦","6♥","8♥"],
      lines: {
        Mercury: ["A♠","J♦","5♦","3♣","A♥","K♠","10♦"],
        Venus: ["K♣","2♥","10♠","6♠","A♦","J♣","9♣"],
        Mars: ["3♥","Q♦","7♦","10♣","K♥","2♠","9♠"],
        Jupiter: ["6♦","4♣","J♥","9♥","3♠","Q♣","7♣"],
        Saturn: ["5♣","4♠","2♦","Q♠","6♣","4♥","8♦"],
        Uranus: ["5♠","3♦","A♣","7♥","5♥","K♦","2♣"],
        Neptune: ["J♠","10♥","9♦","8♣","8♠","7♠","Q♥"]
      },
      emblem: "A♠ (Mercury line, seat 1)"
    },
    planets: {
      Mercury: "Even temper and dispassionate qualities. Smooth running life. But few changes. Contra-indicates the five of hearts under same planet.",
      Venus: "Love and friendship running smoothly and without much variety. Married happiness. Contentment for a season.",
      Mars: "Monotony of life and male forces or strength. In some cases this emblem indicates a long engagement of marriage.",
      Jupiter: "Monotony or long continuation of existing pecuniary affairs. If a co-partnership is shown, it will be long continued. Slow moving life.",
      Saturn: "Sickness of friends or relatives or any other condition under Saturn remains the same. Change, if any, slight under this ruling.",
      Uranus: "Matters appertaining to real estate. One's labor, home and friends remain in a monotonous condition for some time.",
      Neptune: "Contra-indicates journeys under same planet or co-ordinating therewith. If business of person is traveling the indication is reversed."
    } },
  "7_hearts": { name: "Seven of Hearts", solar: 7, spirit: 70, astral: "13138",
    spread: {
      sun: ["5♦","7♥","K♥"],
      lines: {
        Mercury: ["2♠","K♠","6♦","4♣","2♥","A♦","J♦"],
        Venus: ["9♣","3♥","Q♦","7♠","2♦","Q♠","10♣"],
        Mars: ["4♥","8♦","9♠","J♣","9♥","3♠","Q♣"],
        Jupiter: ["7♦","5♣","J♠","10♥","4♠","8♣","8♠"],
        Saturn: ["6♣","5♠","3♦","A♣","7♣","5♥","K♦"],
        Uranus: ["6♠","4♦","2♣","A♠","6♥","9♦","3♣"],
        Neptune: ["A♥","J♥","10♦","K♣","Q♥","10♠","8♥"]
      },
      emblem: "A♠ (Uranus line, seat 4)"
    },
    planets: {
      Mercury: "A sudden and generally an unexpected trouble, soon past. Sudden cooling of a friendship. A fever of short duration.",
      Venus: "An unfaithful friend or lover. A heart ache caused by a friend. A trouble easily overcome. Illness of some friend.",
      Mars: "A broken marriage engagement in some cases. A trouble that lasts some weeks. A friend in trouble or a lawsuit.",
      Jupiter: "Loss through a friend. A friend in some pecuniary trouble. Anxiety caused by money trouble. Illness caused by anxiety.",
      Saturn: "Illness caused by overwork. Illness of some dear friend. A deep and lasting trouble, A secret. Concealment of a bodily infirmity.",
      Uranus: "A warning to be cautious. Trouble with labor. Use care in dealings with a friend. A psychic experience. If with a Queen, it is with a lady.",
      Neptune: "Trouble connected with a journey. Parting from a friend. Inability of self or new friend to make a certain journey."
    } },
  "8_hearts": { name: "Eight of Hearts", solar: 8, spirit: 80, astral: "63147",
    spread: {
      sun: ["10♠","8♥","J♣"],
      lines: {
        Mercury: ["9♥","3♠","Q♦","7♦","5♣","4♠","2♠"],
        Venus: ["K♠","6♣","4♥","2♥","5♠","3♦","A♦"],
        Mars: ["7♣","5♥","K♦","2♦","Q♠","10♥","9♦"],
        Jupiter: ["8♦","9♠","3♣","A♣","J♥","10♦","K♣"],
        Saturn: ["Q♣","J♠","6♠","4♦","8♣","8♠","6♥"],
        Uranus: ["A♥","7♠","5♦","K♥","Q♥","7♥","6♦"],
        Neptune: ["4♣","2♣","A♠","J♦","9♣","3♥","10♣"]
      },
      emblem: "A♠ (Neptune line, seat 3)"
    },
    planets: {
      Mercury: "Sudden power, soon expended. Opera and dancing parties. Gathering of friends and societies. Power and development of love.",
      Venus: "Social and religious gatherings. Spiritual force, power and development. Advancement in soul force. Increase in friendship and love.",
      Mars: "Gatherings or meetings where males predominate. Strong power. Will force. Martial music. Parties where music is by brass bands.",
      Jupiter: "Meetings of friends or fraternal societies. Financial power. Consideration of financial questions. Strength or power of expression.",
      Saturn: "Circles and meetings for psychic investigation. Physicians meetings or societies of like nature. Power in overcoming disease.",
      Uranus: "Labor of love. Friends working together. Spiritual development and power. Psychic force in conjunction with friends.",
      Neptune: "Boating parties. Excursions by water. Power in line of something connected with travel. With 1 h and 2 h, good news from afar."
    } },
  "9_hearts": { name: "Nine of Hearts", solar: 9, spirit: 1, astral: "11471",
    spread: {
      sun: ["8♦","9♥","A♣"],
      lines: {
        Mercury: ["J♥","5♠","K♦","Q♣","7♣","6♠","4♠"],
        Venus: ["2♦","8♠","6♥","4♥","7♠","5♦","3♦"],
        Mars: ["Q♥","7♥","10♦","4♦","2♣","J♠","J♦"],
        Jupiter: ["9♦","8♣","5♣","3♣","A♥","K♠","10♣"],
        Saturn: ["K♣","2♥","10♠","6♦","9♣","8♥","A♠"],
        Uranus: ["3♥","Q♦","7♦","10♥","K♥","2♠","9♠"],
        Neptune: ["6♣","4♣","3♠","A♦","J♣","5♥","Q♠"]
      },
      emblem: "A♠ (Saturn line, seat 7)"
    },
    planets: {
      Mercury: "A sudden disappointment soon over and gone. Overturning of plans by the action of a trusted friend or employee. A love disappointment.",
      Venus: "Disappointment in love. Disappointment in some friend. A heart longing unsatisfied. A misunderstanding. Disapprobation with the conduct of a friend.",
      Mars: "A lovers' misunderstanding. Disappointment caused by a male friend. Jealousy of another person. Injury to a friend or relative.",
      Jupiter: "Loss of time in pursuit of love. Disappointment of strong hopes connected with pecuniary affairs of self or near friends.",
      Saturn: "Misfortune, trouble and disappointment caused by either imprudence, jealousy, lovers' quarrel or illness of self or friends.",
      Uranus: "Want of success in your labors. Disappointment connected with your work. A labor of love. A friend or relative disappoints you in some work.",
      Neptune: "A fruitless journey. Disappointment regarding a visit to friends, or in some cases regarding a journey. A disappointing visit from a distance."
    } },
  "10_hearts": { name: "Ten of Hearts", solar: 10, spirit: 11, astral: "65418",
    spread: {
      sun: ["K♦","10♥","2♣"],
      lines: {
        Mercury: ["J♠","6♠","9♦","8♣","8♠","7♠","5♠"],
        Venus: ["3♦","Q♥","7♥","5♥","10♠","6♦","4♦"],
        Mars: ["8♥","A♠","J♦","5♦","3♣","A♥","K♠"],
        Jupiter: ["10♦","K♣","6♣","4♣","2♥","A♦","J♣"],
        Saturn: ["9♣","3♥","Q♦","7♦","10♣","K♥","2♠"],
        Uranus: ["4♥","8♦","9♠","J♥","9♥","3♠","Q♣"],
        Neptune: ["7♣","5♣","4♠","2♦","Q♠","6♥","A♣"]
      },
      emblem: "A♠ (Mars line, seat 2)"
    },
    planets: {
      Mercury: "A sudden success. Success in love and friendship. Rapid gaining of friends. Strong affection. If with a Queen, success of a lady friend.",
      Venus: "Success, triumph and happiness in friendship and love. A successful love affair. True love from one of the opposite sex for yourself.",
      Mars: "Reunion of old friends. Success in a friendly negotiation. In some cases triumphs of a friend, in some a law case.",
      Jupiter: "Power, success, triumph and happiness. Strength of love and friendship. Help and confidence of friends. Business success based on friendly influences.",
      Saturn: "Power over sickness, sorrow, death, trouble, disappointment, machinations of enemies, scandals and heartburnings. Overcoming or evil influences.",
      Uranus: "Power, success, and good results flowing from your efforts connected with labor and business affairs. Overcoming of some bad influence, by psychic power.",
      Neptune: "Success in a journey. Success in fishing, boating or anything connected with the water. Recovery from any illness caused by dampness."
    } },
  "J_hearts": { name: "Jack of Hearts", solar: 11, spirit: 21, astral: "27268",
    spread: {
      sun: ["9♦","J♥","3♣"],
      lines: {
        Mercury: ["A♥","7♠","10♦","K♣","Q♥","10♠","6♠"],
        Venus: ["4♦","8♥","A♠","6♥","Q♦","7♦","5♦"],
        Mars: ["K♥","2♠","K♠","6♦","4♣","2♥","A♦"],
        Jupiter: ["J♦","9♣","7♣","5♣","3♥","2♦","Q♠"],
        Saturn: ["10♣","4♥","8♦","9♠","J♣","9♥","3♠"],
        Uranus: ["5♥","K♦","Q♣","J♠","10♥","4♠","8♣"],
        Neptune: ["8♠","6♣","5♠","3♦","A♣","7♥","2♣"]
      },
      emblem: "A♠ (Venus line, seat 3)"
    },
    planets: {
      Mercury: "A lover or very close friend. An affectionate and impulsive young man. A friend in sudden need. In some cases it may indicate a son or brother.",
      Venus: "A warm friend or lover. A kind-hearted young man. An amiable gentleman and a true friend. Sometimes a young relative.",
      Mars: "An amiable and good-hearted young man. Engaged to be married in some cases. Deeply religious or spiritual nature. Strong feelings.",
      Jupiter: "A kind friend, a man who is of assistance to you in a pecuniary way. A man of strong affection and soul powers.",
      Saturn: "A good conscientious and true-hearted man, but in trouble and overcome by bad influences. In some cases ill health is the cause.",
      Uranus: "A kind-hearted and industrious young man. Friendly and helpful. He is usually strong in psychic powers. Sometimes a young lover.",
      Neptune: "A gentleman of experience, who has traveled and seen much of the world. A lover who has traveled much. Sailors and traveling men are represented by this card."
    } },
  "Q_hearts": { name: "Queen of Hearts", solar: 12, spirit: 31, astral: "44516",
    spread: {
      sun: ["7♠","Q♥","10♣"],
      lines: {
        Mercury: ["K♥","2♠","10♠","6♦","4♣","3♠","A♠"],
        Venus: ["J♦","5♣","3♥","A♥","4♠","2♦","K♠"],
        Mars: ["6♣","4♥","8♦","A♦","J♣","9♥","K♦"],
        Jupiter: ["Q♦","7♦","2♣","Q♠","10♥","9♦","8♣"],
        Saturn: ["9♠","J♥","5♠","3♦","Q♣","7♣","5♥"],
        Uranus: ["J♠","6♠","4♦","8♥","8♠","6♥","5♦"],
        Neptune: ["3♣","A♣","7♥","10♦","K♣","2♥","9♣"]
      },
      emblem: "A♠ (Mercury line, seat 7)"
    },
    planets: {
      Mercury: "A flighty, merry, light-hearted maiden, who loves parties picnics, balls, etc. Sometimes indicates a female flirt. In other cases a sweetheart.",
      Venus: "A warm-hearted, loving, faithful woman. Disposition of kindness and self-sacrifice. An affectionate sweetheart.",
      Mars: "A faithful, warm-hearted wife or mother. Lady who has some male characteristics regarding business matters. Sometimes a strong and healthy young girl.",
      Jupiter: "A warm-hearted lady of some pecuniary ability and power. A good friend. If matched or co-ordinated with a King, she is married.",
      Saturn: "An affectionate and warm-hearted widow lady. In some cases a divorced woman, but not through her own fault. Usually, unless contra-indicated, in poor health.",
      Uranus: "An industrious, good and faithful woman. May be wife, sister or friend only. A loving mother. Gentle disposition and strong psychic powers sometimes.",
      Neptune: "A good-natured and kindly disposed lady who has traveled a great deal. A good talker. Loves humanity in general. Sometimes rather visionary."
    } },
  "K_hearts": { name: "King of Hearts", solar: 13, spirit: 41, astral: "44518",
    spread: {
      sun: ["Q♦","K♥","Q♠"],
      lines: {
        Mercury: ["10♥","4♠","8♦","9♠","6♣","5♠","3♠"],
        Venus: ["A♦","7♣","5♥","3♥","6♠","4♦","2♦"],
        Mars: ["8♠","6♥","9♦","3♦","A♣","J♥","10♦"],
        Jupiter: ["K♦","Q♣","4♣","2♣","J♠","J♦","9♣"],
        Saturn: ["8♣","A♥","7♠","5♦","K♣","Q♥","7♥"],
        Uranus: ["2♥","10♠","6♦","9♥","8♥","A♠","7♦"],
        Neptune: ["5♣","3♣","2♠","K♠","10♣","4♥","J♣"]
      },
      emblem: "A♠ (Uranus line, seat 6)"
    },
    planets: {
      Mercury: "A middle-aged or elderly gentleman. Quick witted but good tempered and kindly dispositioned. A friend to you.",
      Venus: "A mild mannered, kindly, warm-hearted man. A good friend, or in some cases a near relative by blood or marriage. A kind and affectionate husband.",
      Mars: "A good-hearted man. Usually a married man. A great talker and reasoner. Sometimes a little quick in temper, but soon over it. An old military man in some cases.",
      Jupiter: "A professional man or merchant of much power and force of character. A friend to you. A man of much power in gaining friends.",
      Saturn: "A good, kindly dispositioned friend, who is usually a physician, or in some manner associated with sickness and death. Strong psychic powers under Saturn.",
      Uranus: "A good-hearted, hard working man, who has always worked for the benefit of others. He has powerful psychic forces about him and with him.",
      Neptune: "A kind-hearted man who has traveled a great deal. A great story teller. Sometimes this card indicates an old sailor."
    } },
  "A_clubs": { name: "Ace of Clubs", solar: 14, spirit: 51, astral: "44731",
    spread: {
      sun: ["6♥","A♣","5♦"],
      lines: {
        Mercury: ["3♣","A♥","7♥","10♦","K♣","2♥","J♠"],
        Venus: ["6♠","9♣","8♥","8♠","3♥","Q♦","7♠"],
        Mars: ["10♣","K♥","2♠","10♠","6♦","4♣","3♠"],
        Jupiter: ["A♠","J♦","Q♣","7♦","5♣","4♠","2♦"],
        Saturn: ["K♠","6♣","4♥","8♦","A♦","J♣","9♥"],
        Uranus: ["7♣","5♥","K♦","2♣","Q♠","10♥","9♦"],
        Neptune: ["8♣","9♠","J♥","5♠","3♦","Q♥","4♦"]
      },
      emblem: "A♠ (Jupiter line, seat 1)"
    },
    planets: {
      Mercury: "A wish suddenly formed. An aspiration for knowledge. A letter containing a secret. A piece of news from a short distance.",
      Venus: "Letter, when in conjunction with deuces. A love of knowledge. A wish gratified. Good news in a letter. A telegram with good news.",
      Mars: "Desire for much knowledge. Inquisitiveness. Desire for occult communication. Love of power. Letter from a gentleman, when with a deuce.",
      Jupiter: "Desire for knowledge that may lead to power or preferment. Money or property possessions. With 2 or 5, indicates a business proposition.",
      Saturn: "Letter containing bad news, especially with 2 s and 7 s. A wish which will not be gratified. A longing for the unattainable. Bad news from a sick person.",
      Uranus: "A wish for knowledge regarding some kind of work. Aspirations for advancement in work. Hunger for occult manifestations.",
      Neptune: "A wish to gain knowledge and experience through travel. If followed by a 2 it indicates a letter from a distance. With Jh, news from a traveler far away."
    } },
  "2_clubs": { name: "Two of Clubs", solar: 15, spirit: 61, astral: "36632",
    spread: {
      sun: ["7♥","2♣","6♦"],
      lines: {
        Mercury: ["4♣","2♥","A♠","J♦","9♣","3♥","A♥"],
        Venus: ["7♠","10♣","K♥","Q♥","4♥","8♦","10♠"],
        Mars: ["J♣","9♥","3♠","Q♦","7♦","5♣","4♠"],
        Jupiter: ["2♠","K♠","8♣","9♠","6♣","5♠","3♦"],
        Saturn: ["A♦","7♣","5♥","K♦","2♦","Q♠","10♥"],
        Uranus: ["8♠","6♥","9♦","3♣","A♣","J♥","10♦"],
        Neptune: ["K♣","Q♣","J♠","6♠","4♦","8♥","5♦"]
      },
      emblem: "A♠ (Mercury line, seat 3)"
    },
    planets: {
      Mercury: "Dispute with a hot-headed person. Sudden meeting with a person whom you have had dealings with. With the ace, it means a letter or telegram.",
      Venus: "Unions of acquaintances. Joining in study, of two persons. Information regarding a subject of study. Introduction to an intelligent lady.",
      Mars: "Interview with a gentleman of business. Interview with a reporter. A dispute between two males. A quarrel or lawsuit, under some aspects.",
      Jupiter: "Interview with a gentleman on pecuniary or business affair. A business proposition. Introduction to business man. Joinings and co-partnerships.",
      Saturn: "Interview with a physician or lawyer. Conversation with a person who is ill. A quarrel, under some aspects. A bargain with a professional man.",
      Uranus: "Labor with a person not related to you. Dispute regarding a job of work. Co-partnership in labor. A proposition to use your knowledge for another's benefit.",
      Neptune: "Introduction to a traveled person. Study with a person from another place. A letter, when with an ace. With a personal card, news from person represented."
    } },
  "3_clubs": { name: "Three of Clubs", solar: 16, spirit: 71, astral: "16545",
    spread: {
      sun: ["A♠","3♣","7♦"],
      lines: {
        Mercury: ["5♣","3♥","2♠","K♠","10♣","4♥","2♥"],
        Venus: ["10♠","J♣","9♥","8♥","5♥","K♦","Q♦"],
        Mars: ["Q♠","10♥","4♠","8♦","9♠","6♣","5♠"],
        Jupiter: ["3♠","A♦","K♣","Q♣","7♣","6♠","4♦"],
        Saturn: ["2♦","8♠","6♥","9♦","3♦","A♣","J♥"],
        Uranus: ["Q♥","7♥","10♦","4♣","2♣","J♠","J♦"],
        Neptune: ["9♣","8♣","A♥","7♠","5♦","K♥","6♦"]
      },
      emblem: "A♠ (Sun line, seat 1 / left)"
    },
    planets: {
      Mercury: "Indecision relative to a short journey. Needed in two places at the same time. Undecided as to two lines of study. Two ways open to you.",
      Venus: "Indecision, doubt in an affair of friendship with a lady. Undecided news or doubt regarding a lady friend. Two ways open at once.",
      Mars: "Indecision regarding a transaction with a gentleman. Doubtful news. Knowledge of an undecided character. If followed by an ace, the news comes by letter.",
      Jupiter: "Knowledge regarding a financial transaction, is held in doubt. Undecided in mind relative to a certain bargain or proposition.",
      Saturn: "Indecision, doubt and distrust as to the future, caused by bad influences or ill health. Knowledge of a doubtful character from two places.",
      Uranus: "Doubt and a state of unrest and indecision regarding some line of work or appertaining to a real estate transaction. Doubtful psychic experiences,",
      Neptune: "Indecision relating to a journey to some distance. Doubtful news from far away. Uneasy feeling regarding a distant transaction."
    } },
  "4_clubs": { name: "Four of Clubs", solar: 17, spirit: 81, astral: "54211",
    spread: {
      sun: ["2♠","4♣","9♠"],
      lines: {
        Mercury: ["6♣","4♥","3♠","A♦","J♣","5♥","3♥"],
        Venus: ["Q♦","Q♠","10♥","K♥","6♥","9♦","8♦"],
        Mars: ["A♣","J♥","5♠","K♦","Q♣","7♣","6♠"],
        Jupiter: ["4♠","2♦","9♣","8♣","8♠","7♠","5♦"],
        Saturn: ["3♦","Q♥","7♥","10♦","4♦","2♣","J♠"],
        Uranus: ["8♥","A♠","J♦","5♣","3♣","A♥","K♠"],
        Neptune: ["10♣","K♣","2♥","10♠","6♦","9♥","7♦"]
      },
      emblem: "A♠ (Uranus line, seat 2)"
    },
    planets: {
      Mercury: "Happiness lasting but a short time. A pleasant companion or an interesting book in your company or possession for a short time only.",
      Venus: "Happy home life, comfort and joy. Knowledge of a comforting nature. Enjoyment of spiritual or mental privileges.",
      Mars: "Pleasant and improving conversations with others, especially gentlemen. Happy married life or pleasant home surroundings. Good news from home.",
      Jupiter: "Business contentment. Satisfactory state of money matters. Satisfactory knowledge of pecuniary affairs. Good transaction of a financial character.",
      Saturn: "Good news received from a person who is ill. A happy and contented person, although in ill health, is indicated. Goodness and virtue.",
      Uranus: "Contentment with labor performed. Satisfaction regarding work done by others. Home life and enjoyment. With 10 d, a satisfactory real estate deal.",
      Neptune: "A pleasant journey. Good news or knowledge appertaining to something at a distance. Instructive conversation with a traveler."
    } },
  "5_clubs": { name: "Five of Clubs", solar: 18, spirit: 2, astral: "32342",
    spread: {
      sun: ["3♠","5♣","Q♣"],
      lines: {
        Mercury: ["7♣","5♥","4♠","2♦","Q♠","6♥","4♥"],
        Venus: ["8♦","A♣","J♥","9♥","7♥","10♦","K♦"],
        Mars: ["2♣","J♠","6♠","9♦","8♣","8♠","7♠"],
        Jupiter: ["5♠","3♦","10♣","K♣","Q♥","10♠","6♦"],
        Saturn: ["4♦","8♥","A♠","J♦","5♦","3♣","A♥"],
        Uranus: ["K♥","2♠","K♠","6♣","4♣","2♥","A♦"],
        Neptune: ["J♣","9♣","3♥","Q♦","7♦","10♥","9♠"]
      },
      emblem: "A♠ (Saturn line, seat 3)"
    },
    planets: {
      Mercury: "A sudden and unexpected change of feelings. A change in knowledge and mentality. Sudden news received. Journey to place near by.",
      Venus: "Sudden change in friendship, which may be either way. Change of mind regarding a certain lady friend. The company of an entertaining friend.",
      Mars: "A misunderstanding, causing a change in one's life. Change of opinion regarding a gentleman. A slight quarrel. With 2 c, news of a change in affairs.",
      Jupiter: "A change in pecuniary affairs. Change in the circumstances of a debtor causes a change in your calculations. With a ten, the change will be for the better.",
      Saturn: "Change of plans caused by ill health of self or others. Journey, or short trip, for health, or to see a sick friend. Discontent.",
      Uranus: "A journey, by land only. Change in one's home life. Sale of real estate. Change in mental or psychic powers. Change in knowledge, regarding real estate.",
      Neptune: "A long journey over land and water. A trip by water. News or knowledge of events that are transpiring at a distance."
    } },
  "6_clubs": { name: "Six of Clubs", solar: 19, spirit: 12, astral: "44736",
    spread: {
      sun: ["4♠","6♣","8♣"],
      lines: {
        Mercury: ["8♠","6♥","5♠","3♦","A♣","7♥","5♥"],
        Venus: ["K♦","2♣","J♠","10♥","A♠","J♦","9♦"],
        Mars: ["3♣","A♥","7♠","10♦","K♣","Q♥","10♠"],
        Jupiter: ["6♠","4♦","J♣","9♣","8♥","Q♦","7♦"],
        Saturn: ["5♦","K♥","2♠","K♠","6♦","4♣","2♥"],
        Uranus: ["9♥","3♠","A♦","7♣","5♣","3♥","2♦"],
        Neptune: ["Q♠","10♣","4♥","8♦","9♠","J♥","Q♣"]
      },
      emblem: "A♠ (Venus line, seat 5)"
    },
    planets: {
      Mercury: "Unchangeableness or monotony, lasting for a few days only. Steadfast confidence and esteem for friends. Remaining quiet at home.",
      Venus: "Uniform and unchanging friendship. Knowledge and surroundings remain the same as heretofore. Lack of news. Quiet monotony of life.",
      Mars: "Absence of trouble, quarrels and changes, affecting males principally. Study and improvement goes on steadily and uniformly.",
      Jupiter: "Monotony in business matters. Pecuniary affairs at a standstill, no matter whether good or bad. A lack of news regarding a business transaction.",
      Saturn: "Uniform health or the contrary, according to preceding conditions. Lack of change in the sick. With physicians this card indicates uniformity in business.",
      Uranus: "Unchangeableness in home life, physical and mental surroundings. Monotony in study and labor. This card neutralizes the 5 of clubs.",
      Neptune: "Lack of change relative to travel. Contra-indicates journeys under same or co-ordinate planets. Neutralizes a five under Mercury in same life line."
    } },
  "7_clubs": { name: "Seven of Clubs", solar: 20, spirit: 22, astral: "15253",
    spread: {
      sun: ["5♠","7♣","K♣"],
      lines: {
        Mercury: ["Q♥","7♥","6♠","4♦","2♣","A♠","6♥"],
        Venus: ["9♦","3♣","A♥","J♥","2♠","K♠","10♦"],
        Mars: ["4♣","2♥","10♠","J♦","9♣","8♥","Q♦"],
        Jupiter: ["7♠","5♦","Q♠","10♣","K♥","8♦","9♠"],
        Saturn: ["6♦","9♥","3♠","A♦","7♦","5♣","3♥"],
        Uranus: ["10♥","4♠","2♦","8♠","6♣","4♥","3♦"],
        Neptune: ["A♣","J♣","5♥","K♦","Q♣","J♠","8♣"]
      },
      emblem: "A♠ (Mercury line, seat 6)"
    },
    planets: {
      Mercury: "A trouble that comes suddenly. Bad news from a distance. Inharmony of feelings. Opposition to your projects. An obstacle to gaining knowledge.",
      Venus: "Unfulfilled hopes. Some kind of trouble or quarrel with a woman. Opposition to some belief held by you. A rejected favor or request.",
      Mars: "Opposition from a male. A quarrel or a lawsuit. Trouble in gaining certain knowledge. Antagonism to your wishes and projects.",
      Jupiter: "Trouble on account of some business transaction. Bad news regarding a mercantile firm or corporation. Antagonism from some business firm.",
      Saturn: "A scandal. Backbiting. Ill remarks regarding the person. Illness caused by worry or overstudy. Overthrowing of your plans for advancement in knowledge.",
      Uranus: "Misinformation regarding a piece of work. Trouble with a job of work. Trouble regarding real estate. Antagonizing influences of a psychic nature.",
      Neptune: "Bad news from far away. Trouble with some matter at a distance. An important letter. Antagonizing influences, that come from some one far away."
    } },
  "8_clubs": { name: "Eight of Clubs", solar: 21, spirit: 32, astral: "63642",
    spread: {
      sun: ["J♠","8♣","J♦"],
      lines: {
        Mercury: ["9♣","8♥","A♥","7♠","5♦","K♥","Q♥"],
        Venus: ["7♥","6♦","4♣","2♣","9♥","3♠","A♠"],
        Mars: ["7♦","5♣","3♥","2♠","K♠","10♣","4♥"],
        Jupiter: ["2♥","10♠","3♦","A♦","J♣","5♥","K♦"],
        Saturn: ["Q♦","Q♠","10♥","4♠","8♦","9♠","6♣"],
        Uranus: ["A♣","J♥","5♠","K♣","Q♣","7♣","6♠"],
        Neptune: ["4♦","2♦","8♠","6♥","9♦","3♣","10♦"]
      },
      emblem: "A♠ (Venus line, seat 7)"
    },
    planets: {
      Mercury: "Rapid gaining of knowledge. A rapid development. Meetings for purposes of advancement. Strength and courage. Overcoming of obstacles to advancement.",
      Venus: "Feminine advancement in favor of gaining knowledge. Spiritual development or psychic powers. Represents female schools or gatherings.",
      Mars: "Debates. Male strength and power. Psychic unfoldment and advancement. Represents male schools or gatherings sometimes, of men, for political or other purposes.",
      Jupiter: "Councils and meetings for financial consideration of questions. Power and knowledge, applied to some money making scheme or business.",
      Saturn: "Power to overcome illness or trouble, through knowledge and development. Recovery of a friend who has been ill. Good news from a sick acquaintance.",
      Uranus: "Meetings and gatherings of persons for the consideration of questions connected with labor. Power and knowledge of business or labor. News regarding real estate.",
      Neptune: "Knowledge of matters connected with travel or water. Ability to succeed in such avocations as come under that head."
    } },
  "9_clubs": { name: "Nine of Clubs", solar: 22, spirit: 42, astral: "24926",
    spread: {
      sun: ["2♥","9♣","A♦"],
      lines: {
        Mercury: ["J♣","9♥","3♥","Q♦","7♦","10♥","K♥"],
        Venus: ["2♠","9♠","6♣","4♣","J♥","5♠","3♠"],
        Mars: ["Q♣","7♣","5♥","4♠","2♦","Q♠","6♥"],
        Jupiter: ["4♥","8♦","5♦","3♦","A♣","7♥","10♦"],
        Saturn: ["K♦","2♣","J♠","6♠","9♦","8♣","8♠"],
        Uranus: ["3♣","A♥","7♠","10♣","K♣","Q♥","10♠"],
        Neptune: ["6♦","4♦","8♥","A♠","J♦","5♣","K♠"]
      },
      emblem: "A♠ (Neptune line, seat 4)"
    },
    planets: {
      Mercury: "A sudden disappointment and bad news. Knowledge of a dissatisfying nature. A sudden dislike. Discouragement caused by antagonism to you.",
      Venus: "Disappointment regarding a personal friend; usually a female, under this planet. Disappointment in gaining knowledge. Friendly antagonism to your projects.",
      Mars: "Dislike, distaste, disbelief of some person or thing you are brought into contact with. In some cases a lawsuit. Disappointment caused by lack of knowledge.",
      Jupiter: "Discontent with one's pecuniary affairs. News of money matters, that is disappointing to you. With 7 d, loss of property by the disappointment.",
      Saturn: "Disappointment, discontent or some disquieting feeling caused by illness of self or some one connected with you. Disappointment in gaining knowledge; caused by illness.",
      Uranus: "Disappointment connected with one's business or labor. In some cases a wish to change avocation. Psychic experience of a disappointing character.",
      Neptune: "Disappointment regarding a journey. Generally a long journey, all or partly by water. Discontent with residence. This card neutralizes the 10, of same suit."
    } },
  "10_clubs": { name: "Ten of Clubs", solar: 23, spirit: 52, astral: "65751",
    spread: {
      sun: ["3♥","10♣","2♦"],
      lines: {
        Mercury: ["Q♠","10♥","4♥","8♦","9♠","J♥","9♥"],
        Venus: ["3♠","Q♣","7♣","5♣","J♠","6♠","4♠"],
        Mars: ["8♣","8♠","6♥","5♠","3♦","A♣","7♥"],
        Jupiter: ["5♥","K♦","6♦","4♦","2♣","A♠","J♦"],
        Saturn: ["9♦","3♣","A♥","7♠","10♦","K♣","Q♥"],
        Uranus: ["4♣","2♥","10♠","J♣","9♣","8♥","Q♦"],
        Neptune: ["7♦","5♦","K♥","2♠","K♠","6♣","A♦"]
      },
      emblem: "A♠ (Jupiter line, seat 6)"
    },
    planets: {
      Mercury: "A sudden and sometimes unexpected success. Good news. Success in gaining knowledge. This card neutralizes a 7 c or 9 c next to it.",
      Venus: "Success in friendship. Success in uniting with others in gaining some kind of knowledge or mental growth. Indicates or predicts good news.",
      Mars: "Success in married life. Also in study at home. Applies . more particularly to males, however. General success in professional avocations.",
      Jupiter: "Success and contentment in mercantile or business avocations. Advanced knowledge in your business. Success through learning and mind force.",
      Saturn: "Strength, power and success against the evil effects of Saturn. Overcomes bad influences through knowledge of men and things.",
      Uranus: "Contentment in success, connected with labor. Success in a real estate transaction. General success in agriculture and kindred pursuits.",
      Neptune: "Success on the water. Successful knowledge relating to travel or some affair at a distance. Indicates knowledge necessary for success in traveling."
    } },
  "J_clubs": { name: "Jack of Clubs", solar: 24, spirit: 62, astral: "27844",
    spread: {
      sun: ["4♥","J♣","3♦"],
      lines: {
        Mercury: ["A♣","J♥","5♥","K♦","Q♣","J♠","10♥"],
        Venus: ["4♠","8♣","8♠","6♣","A♥","7♠","5♠"],
        Mars: ["K♣","Q♥","7♥","6♠","4♦","2♣","A♠"],
        Jupiter: ["6♥","9♦","7♦","5♦","3♣","2♠","K♠"],
        Saturn: ["10♦","4♣","2♥","10♠","J♦","9♣","8♥"],
        Uranus: ["5♣","3♥","Q♦","Q♠","10♣","K♥","8♦"],
        Neptune: ["9♠","6♦","9♥","3♠","A♦","7♣","2♦"]
      },
      emblem: "A♠ (Mars line, seat 7)"
    },
    planets: {
      Mercury: "A quick-witted and intelligent young man. In some cases a rival to the person. In some cases a lawyer friend. With odd diamonds at each side, a business rival.",
      Venus: "A jealous young man. Represents one who is full of life. A sharp, bold eyed man. With females, this card indicates a suitor.",
      Mars: "A quarrelsome man. A plotter against some person or persons nearly connected with you. Sometimes an attorney at law.",
      Jupiter: "A man who is making money through his peculiar knowledge regarding a certain line of business. Sometimes indicates a business rival.",
      Saturn: "A rather dissolute young man. Keeps late hours. In some cases it indicates a man you should beware of. With 7 c and 8 c, a studious young man who is in poor health.",
      Uranus: "An industrious young man who has a good knowledge of his business. In some cases a real estate dealer. In certain aspects it represents an intelligent farmer.",
      Neptune: "A jolly rover. A traveling man. In some cases a sailor, lively and full of fun. A young man who possesses knowledge of a wide range."
    } },
  "Q_clubs": { name: "Queen of Clubs", solar: 25, spirit: 72, astral: "43472",
    spread: {
      sun: ["J♥","Q♣","10♦"],
      lines: {
        Mercury: ["K♣","Q♥","J♠","6♠","4♦","8♥","8♠"],
        Venus: ["6♥","5♦","3♣","A♣","K♥","2♠","7♥"],
        Mars: ["6♦","4♣","2♥","A♠","J♦","9♣","3♥"],
        Jupiter: ["A♥","7♠","2♦","K♠","10♣","4♥","8♦"],
        Saturn: ["10♠","J♣","9♥","3♠","Q♦","7♦","5♣"],
        Uranus: ["Q♠","10♥","4♠","8♣","9♠","6♣","5♠"],
        Neptune: ["3♦","A♦","7♣","5♥","K♦","2♣","9♦"]
      },
      emblem: "A♠ (Mars line, seat 4)"
    },
    planets: {
      Mercury: "A smart, lively lady, intelligent and quick witted. Loves parties and plays. A rapid reader. Represents a lady, possessing knowledge of an unusual character.",
      Venus: "An intelligent, accomplished lady, of strong religious or psychic proclivities. Sometimes a beautiful singer or musician.",
      Mars: "A smart woman, but rather quick tempered. In some cases she presents a rather masculine disposition or appearance. A lady of strong will force and power.",
      Jupiter: "A lady of strong powers and force of character. Generally one who makes her own way in the world. A business woman.",
      Saturn: "An intelligent lady, but one who has experienced much sickness and trouble. Sometimes indicates a jealous woman.",
      Uranus: "A hard working, industrious lady, who brings knowledge to bear in her work. One who earns money for herself. In some cases, a farmer's wife.",
      Neptune: "A traveled lady. One who has seen much of the world and has profited thereby, A lady who possesses knowledge that fits her for a stirring life."
    } },
  "K_clubs": { name: "King of Clubs", solar: 26, spirit: 82, astral: "43474",
    spread: {
      sun: ["A♥","K♣","K♠"],
      lines: {
        Mercury: ["10♣","K♥","2♥","10♠","6♦","9♥","8♥"],
        Venus: ["A♠","7♦","5♣","3♣","10♥","4♠","2♠"],
        Mars: ["9♠","6♣","4♥","3♠","A♦","J♣","5♥"],
        Jupiter: ["3♥","Q♦","4♦","2♦","Q♠","6♥","9♦"],
        Saturn: ["8♦","A♣","J♥","5♠","K♦","Q♣","7♣"],
        Uranus: ["2♣","J♠","6♠","9♣","8♣","8♠","7♠"],
        Neptune: ["5♦","3♦","Q♥","7♥","10♦","4♣","J♦"]
      },
      emblem: "A♠ (Venus line, seat 1)"
    },
    planets: {
      Mercury: "A quick tempered man. Smart, lively and witty man. Quick to grasp a point. Kings generally represent married men or men of middle or advanced age.",
      Venus: "A kind-hearted and even tempered gentleman. Usually one who is learned, or following some learned profession. Represents a man of middle age.",
      Mars: "A loud talking overbearing man. Sometimes a military man, or one who leads or commands. A smart, active office holder or politician.",
      Jupiter: "An intelligent reasoner and powerful speaker. In some cases a physician or lawyer. Shows generally a man of \"power.'' With diamonds strong, a merchant.",
      Saturn: "Usually a physician, but one who is not sympathetic. Rather hard-hearted. Inclined to be cross and exacting. An old gentleman who has been a learned man.",
      Uranus: "One who has studied hard and read a great deal. One who has much will power and psychic force. An intelligent worker.",
      Neptune: "An old sailor or sea captain. A smart traveling man. A lover of out door sports, boating, fishing, etc. In some cases a learned man from a distant place."
    } },
  "A_diamonds": { name: "Ace of Diamonds", solar: 27, spirit: 3, astral: "23113",
    spread: {
      sun: ["6♣","A♦","5♠"],
      lines: {
        Mercury: ["3♦","A♣","7♣","5♥","K♦","2♣","Q♠"],
        Venus: ["10♥","9♦","8♣","9♠","3♣","A♥","J♥"],
        Mars: ["10♦","K♣","Q♥","J♠","6♠","4♦","8♥"],
        Jupiter: ["8♠","6♥","Q♦","7♠","5♦","K♥","2♠"],
        Saturn: ["7♥","6♦","4♣","2♥","A♠","J♦","9♣"],
        Uranus: ["7♦","5♣","3♥","2♦","K♠","10♣","4♥"],
        Neptune: ["8♦","10♠","J♣","9♥","3♠","Q♣","4♠"]
      },
      emblem: "A♠ (Saturn line, seat 5)"
    },
    planets: {
      Mercury: "A wish to make money rapidly. A telegram or letter regarding pecuniary matters. A sudden aspiration connected with money.",
      Venus: "Desire for money to be used for a kindly purpose. Wish to do good with wealth. Unselfish wish for wealth. With a ten, the wish will be gratified.",
      Mars: "Wish for money connected in some way with the law. inspiration to succeed in some branch of law. Money letter from a man.",
      Jupiter: "Important message on business. Wish, connected with a large business transaction. Strong aspiration for success in business.",
      Saturn: "Wish to succeed, which is destined to be disappointed, unless strong indications point the other way. Letter or telegram regarding illness of some person.",
      Uranus: "Wish for chance to earn money by labor. Aspiration to succeed in some work to be undertaken. Letter regarding labor matters, when followed by a 2 s or 2 d.",
      Neptune: "Message from a distance. Wish for success connected with travel or business at a distance. News from far away. A wish for money to be used in making a journey."
    } },
  "2_diamonds": { name: "Two of Diamonds", solar: 28, spirit: 13, astral: "32348",
    spread: {
      sun: ["7♣","2♦","6♠"],
      lines: {
        Mercury: ["4♦","2♣","8♠","6♥","9♦","3♣","A♣"],
        Venus: ["J♥","10♦","K♣","Q♣","4♣","2♥","J♠"],
        Mars: ["J♦","9♣","8♥","A♥","7♠","5♦","K♥"],
        Jupiter: ["Q♥","7♥","8♦","10♠","6♦","9♥","3♠"],
        Saturn: ["A♠","7♦","5♣","3♥","2♠","K♠","10♣"],
        Uranus: ["9♠","6♣","4♥","3♦","A♦","J♣","5♥"],
        Neptune: ["K♦","Q♦","Q♠","10♥","4♠","8♣","5♠"]
      },
      emblem: "A♠ (Saturn line, seat 1)"
    },
    planets: {
      Mercury: "A business arrangement very suddenly concluded An unexpected pecuniary offer. A business interview. A telegram on business.",
      Venus: "Introduction to a lady of means. Business arrangement wherein at least one party is a female. Co-partnership with a friend.",
      Mars: "Consultation with a lawyer. Pecuniary bargain with a male. Union of business interests. A business meeting. A letter regarding money.",
      Jupiter: "Business consultation. A pecuniary co-partnership. A combination. Union of monied interests. Business meeting.",
      Saturn: "Interview with a physician. A demand for money. A dunning letter. A bill. An unlucky pecuniary affair. With sevens of any suit, bad news of some kind.",
      Uranus: "Consultation regarding labor. Profitable union of labor interests. Business and labor combined. Labor co-partnership. A real estate transaction.",
      Neptune: "Consultation regarding a business journey. Engagement to travel for another. Money from a distance, particularly when followed by a 4 d or 10 d."
    } },
  "3_diamonds": { name: "Three of Diamonds", solar: 29, spirit: 23, astral: "16311",
    spread: {
      sun: ["8♠","3♦","7♠"],
      lines: {
        Mercury: ["5♦","3♣","Q♥","7♥","10♦","4♣","2♣"],
        Venus: ["J♠","J♦","9♣","8♣","5♣","3♥","A♥"],
        Mars: ["K♠","10♣","K♥","2♥","10♠","6♦","9♥"],
        Jupiter: ["8♥","A♠","K♦","Q♦","7♦","10♥","4♠"],
        Saturn: ["2♠","9♠","6♣","4♥","3♠","A♦","J♣"],
        Uranus: ["Q♣","7♣","5♥","4♦","2♦","Q♠","6♥"],
        Neptune: ["9♦","8♦","A♣","J♥","5♠","K♣","6♠"]
      },
      emblem: "A♠ (Jupiter line, seat 2)"
    },
    planets: {
      Mercury: "A sudden indecision arises regarding a pecuniary matter. Two business ways open at once. A feeling of uneasy insecurity. Doubt and distrust regarding business.",
      Venus: "Indecision relating to money affairs and a lady. Regarding a certain friend and a money matter. Choice between two propositions.",
      Mars: "An undecided pecuniary affair with a male. A lawsuit in a state of uncertainty. An uncertain trouble arises. Doubt regarding a pecuniary transaction.",
      Jupiter: "An undecided business investment. Indecision connected with a large transaction. Two ways open at once in pecuniary affairs. Uncertainty and doubt.",
      Saturn: "Uncertainty caused by death, or perhaps only illness. A feeling of insecurity regarding future pecuniary transaction.",
      Uranus: "A real estate transaction held in suspense. Uncertain outcome to a labor matter. Two ways open at once. Choice of two kinds of labor, both fair.",
      Neptune: "Uncertainty and indecision connected with money, a journey or some matter at a distance. Doubt and general indecision regarding future home and business."
    } },
  "4_diamonds": { name: "Four of Diamonds", solar: 30, spirit: 33, astral: "43771",
    spread: {
      sun: ["Q♥","4♦","10♠"],
      lines: {
        Mercury: ["6♦","4♣","8♥","A♠","J♦","5♣","3♣"],
        Venus: ["A♥","K♠","10♣","K♣","6♣","4♥","2♥"],
        Mars: ["A♦","J♣","9♥","3♥","Q♦","7♦","10♥"],
        Jupiter: ["K♥","2♠","9♦","8♦","9♠","J♥","5♠"],
        Saturn: ["3♠","Q♣","7♣","5♥","4♠","2♦","Q♠"],
        Uranus: ["8♣","8♠","6♥","5♦","3♦","A♣","7♥"],
        Neptune: ["10♦","K♦","2♣","J♠","6♠","9♣","7♠"]
      },
      emblem: "A♠ (Mercury line, seat 4)"
    },
    planets: {
      Mercury: "Your hopes will be suddenly realized. Satisfaction in a pecuniary affair. Indecision comes to an end. Sudden receipt of money when hardly expected.",
      Venus: "Satisfaction regarding a money affair and a lady. In come cases a dear friend. Adjustment of pecuniary difficulties. General satisfaction of mind as regards money.",
      Mars: "Termination of a law case. Satisfaction regarding money and a certain man. Happy ending of a trouble. This card counteracts the 5 and 7 of diamonds.",
      Jupiter: "An investment turns out satisfactorily. Satisfaction obtained connected with money. A good business. Expresses general good business.",
      Saturn: "Lost money restored. A recovery of health causes satisfaction in a pecuniary way. A will in person's favor, when it follows a seven of spades, especially.",
      Uranus: "Work prospers. Satisfaction in your labor. Pleasant business prospects. Happy work. Money gained by labor. A satisfactory real estate deal.",
      Neptune: "A satisfactory journey. Matters turn out well at a distance. Satisfaction regarding business connected with travel. Money gained by travel."
    } },
  "5_diamonds": { name: "Five of Diamonds", solar: 31, spirit: 43, astral: "34133",
    spread: {
      sun: ["8♥","5♦","Q♦"],
      lines: {
        Mercury: ["7♦","5♣","K♥","2♠","K♠","6♣","4♣"],
        Venus: ["2♥","A♦","J♣","9♣","7♣","5♥","3♥"],
        Mars: ["2♦","Q♠","10♥","4♥","8♦","9♠","J♥"],
        Jupiter: ["9♥","3♠","10♦","K♦","Q♣","J♠","6♠"],
        Saturn: ["4♠","8♣","8♠","6♥","5♠","3♦","A♣"],
        Uranus: ["K♣","Q♥","7♥","6♦","4♦","2♣","A♠"],
        Neptune: ["J♦","9♦","3♣","A♥","7♠","10♣","10♠"]
      },
      emblem: "A♠ (Uranus line, seat 7)"
    },
    planets: {
      Mercury: "A sudden or unexpected change, affecting the pecuniary status or arrangements of person, or one connected in a business way.",
      Venus: "Change in love or friendship, caused by some pecuniary considerations. Financial change connected with a lady or dear friend. Followed by 10 d, the change is a good one.",
      Mars: "Change happening to a male. A journey on business. A money transaction changes in consequence of the interference of a gentleman in same business.",
      Jupiter: "A business journey. Change of business. Financial change. Change of an investment. A pecuniary cross to bear, in some cases.",
      Saturn: "Change of business, location or advantage through sickness, misfortune or death. This card is counteracted by the 6 d under Saturn.",
      Uranus: "Change of location of one's labor. A change of home. A long journey by land. A real estate transaction. This card represents a pecuniary change of some sort,",
      Neptune: "A change of a pecuniary character, appearing sometimes at a distance. A long journey on business. This card is counteracted by 6d or 6 s under planet Neptune."
    } },
  "6_diamonds": { name: "Six of Diamonds", solar: 32, spirit: 53, astral: "44583",
    spread: {
      sun: ["K♥","6♦","8♦"],
      lines: {
        Mercury: ["9♠","6♣","9♥","3♠","A♦","7♣","5♣"],
        Venus: ["3♥","2♦","Q♠","10♣","8♠","6♥","4♥"],
        Mars: ["3♦","A♣","J♥","5♥","K♦","Q♣","J♠"],
        Jupiter: ["10♥","4♠","J♦","9♦","8♣","A♥","7♠"],
        Saturn: ["5♠","K♣","Q♥","7♥","6♠","4♦","2♣"],
        Uranus: ["9♣","8♥","A♠","7♦","5♦","3♣","2♠"],
        Neptune: ["K♠","10♦","4♣","2♥","10♠","J♣","Q♦"]
      },
      emblem: "A♠ (Uranus line, seat 3)"
    },
    planets: {
      Mercury: "Matters will soon settle down smoothly in a financial way. You will not make a business journey at present. Counteracts the five of diamonds.",
      Venus: "Money affairs move strongly in a monotonous way. No particular change with friends. Contra-indicates the five of hearts and diamonds under Venus.",
      Mars: "Affects money matters of males principally. Settlement of financial difficulties. Smooth moving of financial arrangements. Counteracts the 5 d and 7 d under Mars.",
      Jupiter: "Settlement of accounts. Business matters running slowly along. Remain unchanged whether good or bad. Expresses general lack of excitement.",
      Saturn: "Monotonous life which is quite apt to lead to ennui or illness. Sameness or want of change in pecuniary affairs. Counteracts the 5 and 7 of diamonds.",
      Uranus: "Location of work remains the same. Monotonous labor. Real estate matters in statu quo. Counteracts the five of diamonds and the five of spades.",
      Neptune: "Chances for travel very poor. Counteracts one five under this planet. With two fives, it indicates a monotonous and long journey on business."
    } },
  "7_diamonds": { name: "Seven of Diamonds", solar: 33, spirit: 63, astral: "13318",
    spread: {
      sun: ["9♥","7♦","K♦"],
      lines: {
        Mercury: ["Q♣","7♣","10♥","4♠","2♦","8♠","6♣"],
        Venus: ["4♥","3♦","A♣","J♣","Q♥","7♥","5♥"],
        Mars: ["4♦","2♣","J♠","6♥","9♦","8♣","A♥"],
        Jupiter: ["J♥","5♠","K♠","10♦","K♣","2♥","10♠"],
        Saturn: ["6♠","9♣","8♥","A♠","7♠","5♦","3♣"],
        Uranus: ["10♣","K♥","2♠","9♠","6♦","4♣","3♠"],
        Neptune: ["A♦","J♦","5♣","3♥","Q♦","Q♠","8♦"]
      },
      emblem: "A♠ (Saturn line, seat 4)"
    },
    planets: {
      Mercury: "Unexpected call for money. Trouble regarding a pecuniary matter. Sudden and unexpected loss of money or property of some kind.",
      Venus: "Money paid or given to a lady. Trouble connected with money and a friend, or near relative. With 8h, money paid out for some pleasure.",
      Mars: "Loss of money through the law. Money paid out to a man. In some cases a lawsuit, when with 7 c, especially. Indicates trouble connected with money, generally.",
      Jupiter: "Investment of money in some place where you will not see it again soon. Loss of money in a trade. Use care when this card comes under Jupiter.",
      Saturn: "Loss of money through illness of self or some other person. Misfortune or bad acts of another. If followed by 7 s and 10 s it is by death of some one.",
      Uranus: "Money paid out for labor. Investment in land. Paid out for some psychic manifestation. Loss of money for labor done.",
      Neptune: "Money paid out or entirely lost through something connected with travel or some operation at a distance. Counteracts the eight of diamonds."
    } },
  "8_diamonds": { name: "Eight of Diamonds", solar: 34, spirit: 73, astral: "63651",
    spread: {
      sun: ["Q♠","8♦","6♥"],
      lines: {
        Mercury: ["9♦","8♣","A♣","J♥","5♠","K♣","Q♣"],
        Venus: ["7♣","6♠","4♦","2♦","9♣","8♥","8♠"],
        Mars: ["7♠","5♦","3♣","Q♥","7♥","10♦","4♣"],
        Jupiter: ["2♣","J♠","3♠","A♠","J♦","5♣","3♥"],
        Saturn: ["A♥","K♠","10♣","K♥","2♥","10♠","6♦"],
        Uranus: ["A♦","J♣","9♥","K♦","Q♦","7♦","10♥"],
        Neptune: ["4♠","2♠","9♠","6♣","4♥","3♦","5♥"]
      },
      emblem: "A♠ (Jupiter line, seat 4)"
    },
    planets: {
      Mercury: "Sudden accession of power. Rapid gaining of ends sought, when related to money matters. Meetings for pecuniary purposes. Overcoming of trouble shown by 7 d.",
      Venus: "Power of gaining property through the ability to make friends. Indicates female financial ability. Money made through psychic gifts.",
      Mars: "Power gained through numbers. Meetings of males for financial consideration of questions. Strength, financially and commercially.",
      Jupiter: "Meetings of stockholders and companies, corporations and societies. Power and ability to make money. Sometimes represents quite large pecuniary transactions.",
      Saturn: "Meetings of physicians. Power and financial ability connected with illness or death. In most cases represents gain by what is a loss to others.",
      Uranus: "Labor meetings. Power of making money through labor. Power gained through psychic gifts. To make money through power of foresight.",
      Neptune: "Power to gain money through travel. Sale of goods or property at a distance. Financial power in large concerns extending to far-away places."
    } },
  "9_diamonds": { name: "Nine of Diamonds", solar: 35, spirit: 83, astral: "14486",
    spread: {
      sun: ["2♣","9♦","A♠"],
      lines: {
        Mercury: ["J♦","9♣","3♣","A♥","7♠","10♣","K♣"],
        Venus: ["Q♥","10♠","6♦","4♦","J♣","9♥","8♥"],
        Mars: ["Q♦","7♦","5♣","K♥","2♠","K♠","6♣"],
        Jupiter: ["4♣","2♥","5♠","3♠","A♦","7♣","5♥"],
        Saturn: ["3♥","2♦","Q♠","10♥","4♥","8♦","9♠"],
        Uranus: ["3♦","A♣","J♥","10♦","K♦","Q♣","J♠"],
        Neptune: ["6♠","4♠","8♣","8♠","6♥","5♦","7♥"]
      },
      emblem: "A♠ (Sun line, seat 3 / right)"
    },
    planets: {
      Mercury: "Financial disappointment, generally coming suddenly or connected with some speculation. Disappointment regarding a short journey.",
      Venus: "Disappointment of a lady, connected in some way with money. Love affair goes wrong on account of finances. Counteracted by 8 d or 10 d under Venus.",
      Mars: "Disappointment of a gentleman in some financial way. Pecuniary dissatisfaction and trouble. Loss of money by a lawsuit in certain aspects.",
      Jupiter: "Loss of money through some mercantile transaction. Investment of money that will bring no return in cash or property.",
      Saturn: "Investment in some losing enterprise. Disappointment of hopes regarding financial matters, caused by illness and in some aspects by death.",
      Uranus: "Disappointment connected with a deal in real estate. Loss of money on labor. In some cases loss of a job or position where labor is employed.",
      Neptune: "Disappointment connected with travel or a long journey, caused by financial trouble. Money paid out for travel, sometimes."
    } },
  "10_diamonds": { name: "Ten of Diamonds", solar: 36, spirit: 4, astral: "43647",
    spread: {
      sun: ["3♣","10♦","2♠"],
      lines: {
        Mercury: ["K♠","10♣","4♣","2♥","10♠","J♣","9♣"],
        Venus: ["8♥","Q♦","7♦","5♦","Q♠","10♥","K♥"],
        Mars: ["8♦","9♠","6♣","9♥","3♠","A♦","7♣"],
        Jupiter: ["5♣","3♥","6♠","4♠","2♦","8♠","6♥"],
        Saturn: ["4♥","3♦","A♣","J♥","5♥","K♦","Q♣"],
        Uranus: ["4♦","2♣","J♠","J♦","9♦","8♣","A♥"],
        Neptune: ["7♠","5♠","K♣","Q♥","7♥","6♦","A♠"]
      },
      emblem: "A♠ (Neptune line, seat 7)"
    },
    planets: {
      Mercury: "Success in a speculation. Financial success coming suddenly. Success of a short journey. A \" streak of good fortune.\"",
      Venus: "In some aspects a wealthy marriage. A wealthy acquaintance. Success in friends and money. Kind help of a friend in some cases.",
      Mars: "Success in a lawsuit. Financial success of a male connected with person. In some cases represents money gained by matrimony.",
      Jupiter: "General success in financial matters. Shows the planets to be favorable for pecuniary enterprises of any or all kinds, unless the card is aspected against.",
      Saturn: "Success in money matters, but will not long continue. Success impeded through ill health, or death of some other person,",
      Uranus: "General success in a pecuniary way with labor, business and real property. Success in selling property. Success in occult matters and those connected with land.",
      Neptune: "Success in gaining money by travel. Selling goods on the road by sample. Also in business connected with the water, such as shipping."
    } },
  "J_diamonds": { name: "Jack of Diamonds", solar: 37, spirit: 14, astral: "25261",
    spread: {
      sun: ["4♣","J♦","3♠"],
      lines: {
        Mercury: ["A♦","J♣","5♣","3♥","Q♦","Q♠","10♣"],
        Venus: ["K♥","8♦","9♠","6♦","A♣","J♥","9♥"],
        Mars: ["K♦","Q♣","7♣","10♥","4♠","2♦","8♠"],
        Jupiter: ["6♣","4♥","7♠","5♠","3♦","Q♥","7♥"],
        Saturn: ["5♥","4♦","2♣","J♠","6♥","9♦","8♣"],
        Uranus: ["5♦","3♣","A♥","K♠","10♦","K♣","2♥"],
        Neptune: ["10♠","6♠","9♣","8♥","A♠","7♦","2♠"]
      },
      emblem: "A♠ (Neptune line, seat 5)"
    },
    planets: {
      Mercury: "A young man who spends money freely and makes money easily. In some cases a railroad man, or connected with something rapid.",
      Venus: "A gentleman with a good income. A generous man. A' free-hearted lover or young friend. In some cases a clerk in a business house,",
      Mars: "Usually a young married man. Sometimes a middle aged single man. An attorney at law. A law clerk. A bank clerk or cashier.",
      Jupiter: "A well-to-do man. A merchant, salesman, banker, cashier, broker or something of that nature. One who handles considerable money.",
      Saturn: "A man who has fine business qualities, but is hampered by ill health. In some cases this emblem indicates a wild dissipated man.",
      Uranus: "An industrious young man who makes considerable money by his own exertions. In some aspects, a writer who makes money by his pen.",
      Neptune: "A man who makes money by traveling. In general terms a traveling salesman or agent for some monied concern."
    } },
  "Q_diamonds": { name: "Queen of Diamonds", solar: 38, spirit: 24, astral: "33842",
    spread: {
      sun: ["J♣","Q♦","5♥"],
      lines: {
        Mercury: ["K♦","Q♣","Q♠","10♥","4♠","8♣","9♠"],
        Venus: ["6♣","5♠","3♦","A♦","K♣","Q♥","7♣"],
        Mars: ["6♠","4♦","2♣","8♠","6♥","9♦","3♣"],
        Jupiter: ["A♣","J♥","2♠","7♥","10♦","4♣","2♥"],
        Saturn: ["J♠","J♦","9♣","8♥","A♥","7♠","5♦"],
        Uranus: ["K♠","10♣","K♥","8♦","10♠","6♦","9♥"],
        Neptune: ["3♠","A♠","7♦","5♣","3♥","2♦","4♥"]
      },
      emblem: "A♠ (Neptune line, seat 2)"
    },
    planets: {
      Mercury: "A lady who loves excitement; parties, operas and every place where wealth is displayed. She loves money and luxury.",
      Venus: "A warm-hearted, charitable lady who has considerable means. In some cases a wealthy lady friend of person. In some aspects an actress or singer.",
      Mars: "Usually a married lady. One who spends money freely. She is fond of dress and generally quite pleased with the admiration of the opposite sex.",
      Jupiter: "A wealthy lady, or one who is closely connected with a gentleman who handles money. Such as a business man or banker.",
      Saturn: "A lady with money or business ability, but hampered by ill health. In some cases she is a physician. This card is an excellent one for physicians, under Saturn.",
      Uranus: "An industrious and energetic lady who makes money by her own exertions. In some cases she has strong psychic or occult gifts which she utilizes.",
      Neptune: "A traveled lady; one who has spent a great deal of money in seeing the world. In some cases an actress or opera singer."
    } },
  "K_diamonds": { name: "King of Diamonds", solar: 39, spirit: 34, astral: "37651",
    spread: {
      sun: ["A♣","K♦","7♥"],
      lines: {
        Mercury: ["10♦","K♣","2♣","J♠","6♠","9♣","8♣"],
        Venus: ["8♠","7♠","5♦","3♦","10♣","K♥","Q♥"],
        Mars: ["10♠","6♦","4♣","8♥","A♠","J♦","5♣"],
        Jupiter: ["3♣","A♥","4♠","2♠","K♠","6♣","4♥"],
        Saturn: ["2♥","A♦","J♣","9♥","3♥","Q♦","7♦"],
        Uranus: ["2♦","Q♠","10♥","9♦","8♦","9♠","J♥"],
        Neptune: ["5♠","3♠","Q♣","7♣","5♥","4♦","6♥"]
      },
      emblem: "A♠ (Mars line, seat 5)"
    },
    planets: {
      Mercury: "A sharp, quick, active, money-making business man. Sometimes a speculator. One who makes money fluctuatingly.",
      Venus: "A wealthy lover. A wealthy friend. An actor or musician. A business man with kind heart, who makes much money.",
      Mars: "In some cases a wealthy husband. A well-to-do lawyer, or one who owns or controls mines and minerals. A man of strong money-making power.",
      Jupiter: "A wealthy, money-making, proud, \"self-made\" man, who, as has been said, \"loves his maker.'' In some cases a banker, wholesale dealer or manufacturer.",
      Saturn: "A rich man who is very close with his money. In some cases a miserly man. Under some aspects a man of wealth who is in ill health.",
      Uranus: "A wealthy man who labors hard to make more money. In some cases a large real estate dealer. A gentleman of much psychic power.",
      Neptune: "A man who has spent much money in travel. Sometimes a merchant or seafaring man who has made a great deal of money."
    } },
  "A_spades": { name: "Ace of Spades", solar: 40, spirit: 44, astral: "56575",
    spread: {
      sun: ["6♦","A♠","9♥"],
      lines: {
        Mercury: ["3♠","A♦","7♦","5♣","3♥","2♦","K♠"],
        Venus: ["10♣","4♥","8♦","10♠","3♦","A♣","J♣"],
        Mars: ["5♥","K♦","Q♣","Q♠","10♥","4♠","8♣"],
        Jupiter: ["9♠","6♣","A♥","J♥","5♠","K♣","Q♥"],
        Saturn: ["7♣","6♠","4♦","2♣","8♠","6♥","9♦"],
        Uranus: ["7♠","5♦","3♣","2♠","7♥","10♦","4♣"],
        Neptune: ["2♥","J♠","J♦","9♣","8♥","Q♦","K♥"]
      },
      emblem: "A♠ (Sun line, seat 2 / center — the focus card)"
    },
    planets: {
      Mercury: "A secret wish. A secret resolution. A secret knowledge. A secret society. With mystics it represents the Order of the Magi.",
      Venus: "A letter containing a secret. A secret love. A secret wish. A secret friend. A secret or occult society or secret order. A secret present to person.",
      Mars: "A secret shared by a male. A marriage secret. A secret wish. A secret communication. A letter with bad news in some cases. A conspiracy or plot.",
      Jupiter: "A secret mercantile business or speculative transaction. A secret personal business letter. An important letter. A 1 secret order.",
      Saturn: "Bad news by letter. A secret communication. In some cases a secret disease or a concealed trouble. A concealed disappointment. A secret kept from you.",
      Uranus: "A secret journey by land. A secret real estate transaction. Secret or occult psychic power. A secret present. A hidden will.",
      Neptune: "A journey by water on secret business. News of a private nature from a distance. A letter on private business. Visit of a person on some secret mission."
    } },
  "2_spades": { name: "Two of Spades", solar: 41, spirit: 54, astral: "36731",
    spread: {
      sun: ["7♦","2♠","10♥"],
      lines: {
        Mercury: ["4♠","2♦","9♠","6♣","4♥","3♦","A♦"],
        Venus: ["J♣","5♥","K♦","Q♦","4♦","2♣","Q♠"],
        Mars: ["6♥","9♦","8♣","A♣","J♥","5♠","K♣"],
        Jupiter: ["Q♣","7♣","2♥","J♠","6♠","9♣","8♥"],
        Saturn: ["8♠","7♠","5♦","3♣","Q♥","7♥","10♦"],
        Uranus: ["10♠","6♦","4♣","3♠","A♠","J♦","5♣"],
        Neptune: ["3♥","A♥","K♠","10♣","K♥","8♦","9♥"]
      },
      emblem: "A♠ (Uranus line, seat 5)"
    },
    planets: {
      Mercury: "A pressing engagement. An agreement to work for another. An unexpected offer of a piece of work. A sudden union.",
      Venus: "A union with a lady in some kind of work. A joining of forces. A proposal of a business nature. A copartnership with a relative or near friend.",
      Mars: "Work in conjunction with a man. Consultation with a lawyer. A combination or plot. A letter from a male. A union of male forces in some kind of labor.",
      Jupiter: "Interview with a business man relating to work. Letter regarding a piece of work. A transaction between two persons.",
      Saturn: "Letter announcing the illness of a person you are interested in. News regarding a sick friend. Consultation with a physician. A business call on the sick.",
      Uranus: "Work done by two persons jointly. Letter regarding a piece of work. News of the illness of a person at a distance, by land. Plan of work between two,",
      Neptune: "Interview with a person regarding travel on business. News from a distance over water and land. A work at a distance from your residence."
    } },
  "3_spades": { name: "Three of Spades", solar: 42, spirit: 64, astral: "13161",
    spread: {
      sun: ["9♠","3♠","J♥"],
      lines: {
        Mercury: ["5♠","3♦","Q♣","7♣","5♥","4♦","2♦"],
        Venus: ["Q♠","6♥","9♦","8♦","5♦","3♣","A♣"],
        Mars: ["7♥","10♦","K♣","2♣","J♠","6♠","9♣"],
        Jupiter: ["8♣","8♠","3♥","A♥","7♠","10♣","K♥"],
        Saturn: ["Q♥","10♠","6♦","4♣","8♥","A♠","J♦"],
        Uranus: ["Q♦","7♦","5♣","4♠","2♠","K♠","6♣"],
        Neptune: ["4♥","2♥","A♦","J♣","9♥","K♦","10♥"]
      },
      emblem: "A♠ (Saturn line, seat 6)"
    },
    planets: {
      Mercury: "A case arises suddenly where you must decide between two courses. Two ways open at once. Two offers of some kind, relating to work.",
      Venus: "Indecision regarding a matter of work or health, connected with a woman. Undecided bargain with a friend. Indecision regarding a home.",
      Mars: "Undecided business matter. Business indecision. Two ways open in business, both requiring much work. Indecision regarding a law case.",
      Jupiter: "Indecision regarding a cash transaction. Two kinds of business, both requiring much cash to conduct, open up at once for the person.",
      Saturn: "Indecision caused by a death or illness. An undecided case of illness. An unsettled bill, in some cases. A lingering illness.",
      Uranus: "Indecision relative to a psychic experience, a real estate transaction, a job of work, a land journey or the conduct of some employee.",
      Neptune: "Indecision regarding a journey by water, a business at a distance. The visit of a friend, a job of work on the water, or connected with transportation."
    } },
  "4_spades": { name: "Four of Spades", solar: 43, spirit: 74, astral: "54472",
    spread: {
      sun: ["Q♣","4♠","J♠"],
      lines: {
        Mercury: ["6♠","4♦","8♣","8♠","6♥","5♦","3♦"],
        Venus: ["A♣","7♥","10♦","K♦","6♦","4♣","2♣"],
        Mars: ["A♠","J♦","9♣","3♣","A♥","7♠","10♣"],
        Jupiter: ["K♣","Q♥","4♥","2♥","10♠","J♣","9♥"],
        Saturn: ["8♥","Q♦","7♦","5♣","K♥","2♠","K♠"],
        Uranus: ["8♦","9♠","6♣","5♠","3♠","A♦","7♣"],
        Neptune: ["5♥","3♥","2♦","Q♠","10♥","9♦","J♥"]
      },
      emblem: "A♠ (Mars line, seat 1)"
    },
    planets: {
      Mercury: "Realizations of expectations coming suddenly. Unlocked for success in some piece of work. A case decided suddenly. Satisfaction, of limited duration.",
      Venus: "Love for your work. Work for others through love for them. Satisfaction in your labors. A happy home life. Contentment of soul.",
      Mars: "Married happiness for females. Strength in labor of love for males. Satisfactory labor at home. Counteracts the five of spades and seven of spades.",
      Jupiter: "Satisfactory labor. Good pecuniary returns therefor. Reasonable compensation for labor performed and satisfaction gained thereby.",
      Saturn: "Recovery from illness. Satisfactory ending of a trouble or disappointment. Counteracts the seven of spades under same planet.",
      Uranus: "Satisfaction derived from one's business or labor. Satisfaction from news received from a distance. Labor connected with the farm.",
      Neptune: "Success in travel connected with business or labor. Satisfactory journey by water, when a five comes under the same or a co-ordinate planet."
    } },
  "5_spades": { name: "Five of Spades", solar: 44, spirit: 84, astral: "27824",
    spread: {
      sun: ["8♣","5♠","A♥"],
      lines: {
        Mercury: ["7♠","5♦","K♣","Q♥","7♥","6♦","4♦"],
        Venus: ["2♣","A♠","J♦","9♦","7♦","5♣","3♣"],
        Mars: ["2♠","K♠","10♣","4♣","2♥","10♠","J♣"],
        Jupiter: ["9♣","8♥","5♥","3♥","Q♦","Q♠","10♥"],
        Saturn: ["K♥","8♦","9♠","6♣","9♥","3♠","A♦"],
        Uranus: ["K♦","Q♣","7♣","6♠","4♠","2♦","8♠"],
        Neptune: ["6♥","4♥","3♦","A♣","J♥","10♦","J♠"]
      },
      emblem: "A♠ (Venus line, seat 2)"
    },
    planets: {
      Mercury: "A sudden journey. A change of employment. A change in business methods. News regarding a distant transaction.",
      Venus: "Change in the labor of a female. Journey of a lady by land. Removal of home or habitation. Visit of a female. A short journey.",
      Mars: "Change in employment of a male. Visit of a male from a city. A journey connected with business or one's labor. A change in one's usual life and home surroundings.",
      Jupiter: "Change in pecuniary affairs. Pecuniary change in one's labor. Journey on business. News of a business nature.",
      Saturn: "Change of employment caused by illness of self or friends. A journey or removal caused by an illness. In some cases it represents an unfortunate journey.",
      Uranus: "Journey connected with business, profession or labor. Change in one's profession or work. A change, connected with real estate or agriculture.",
      Neptune: "Journey to a distance, professional or connected with some kind of work. News from a distance regarding a change."
    } },
  "6_spades": { name: "Six of Spades", solar: 45, spirit: 5, astral: "44754",
    spread: {
      sun: ["K♣","6♠","2♥"],
      lines: {
        Mercury: ["10♠","6♦","9♣","8♥","A♠","7♦","5♦"],
        Venus: ["3♣","2♠","K♠","10♦","9♠","6♣","4♣"],
        Mars: ["3♠","A♦","J♣","5♣","3♥","Q♦","Q♠"],
        Jupiter: ["10♣","K♥","6♥","4♥","8♦","A♣","J♥"],
        Saturn: ["9♥","K♦","Q♣","7♣","10♥","4♠","2♦"],
        Uranus: ["9♦","8♣","8♠","7♠","5♠","3♦","Q♥"],
        Neptune: ["7♥","5♥","4♦","2♣","J♠","J♦","A♥"]
      },
      emblem: "A♠ (Mercury line, seat 5)"
    },
    planets: {
      Mercury: "Counteracts changes shown under same planet. End to worry. Settlement of difficulties. Steady and satisfactory employment.",
      Venus: "Quiet, uneventful life as regards self and intimate friends and surroundings. Matters move smoothly. This card indicates quiet and comfort for females.",
      Mars: "Settlement of lawsuits, quarrels or anything of the kind shown under this planet. Absence of change or excitement generally.",
      Jupiter: "Monotony in business or professional life. Business moving smoothly. Counteracts fives and sevens under same planet.",
      Saturn: "Recovery from illness when same is shown. Counteracts changes and troubles shown under this planet. Followed by 4d, satisfactory and steady employment.",
      Uranus: "Prosperity in profession or labor, or the contrary, remains without change for some time. Monotony in profession or labor.",
      Neptune: "If a journey is shown it is a long and dreary one. In general this emblem indicates \" no journey will be made.\" Contra-indicates the five and seven of same suit."
    } },
  "7_spades": { name: "Seven of Spades", solar: 46, spirit: 15, astral: "17782",
    spread: {
      sun: ["9♣","7♠","3♥"],
      lines: {
        Mercury: ["Q♦","7♦","10♣","K♥","2♠","9♠","6♦"],
        Venus: ["4♣","3♠","A♦","J♦","Q♣","7♣","5♣"],
        Mars: ["4♠","2♦","Q♠","6♣","4♥","8♦","A♣"],
        Jupiter: ["J♣","9♥","7♥","5♥","K♦","2♣","J♠"],
        Saturn: ["10♥","9♦","8♣","8♠","J♥","5♠","3♦"],
        Uranus: ["10♦","K♣","Q♥","10♠","6♠","4♦","8♥"],
        Neptune: ["A♠","6♥","5♦","3♣","A♥","K♠","2♥"]
      },
      emblem: "A♠ (Neptune line, seat 1)"
    },
    planets: {
      Mercury: "Headache, severe throbbing. Trouble in some matter connected with your work. Sudden accident or illness. Counteracts the eight of spades.",
      Venus: "Illness caused by overdoing, late hours or excitement. A love, trouble or illness of a dear friend. Counteracts the seven of hearts.",
      Mars: "Illness caused by excitement, drink, late hours, passion or severe labor. Chills, cold feet and hands. Represents trouble for males and for females trouble caused by males.",
      Jupiter: "Illness caused by business worry. Indicates considerable trouble and care. Sleeplessness, headache, pain in the loins and back. ,",
      Saturn: "Illness and trouble connected with the rulings under Scorpio. This class of diseases need not be particularized here. Followed by a 4 d, a will in your favor.",
      Uranus: "Trouble with one's work or profession. An obstacle to overcome. Illness caused by overwork. Some work is not satisfactory.",
      Neptune: "Illness similar to sea sickness. Rheumatism and other diseases caused by dampness. Dropsy. Trouble, or some obstacle, to a journey."
    } },
  "8_spades": { name: "Eight of Spades", solar: 47, spirit: 25, astral: "63388",
    spread: {
      sun: ["6♠","8♠","9♣"],
      lines: {
        Mercury: ["8♥","A♠","7♠","5♦","3♣","2♠","7♥"],
        Venus: ["10♦","4♣","2♥","J♠","3♠","A♦","J♦"],
        Mars: ["5♣","3♥","Q♦","K♠","10♣","K♥","8♦"],
        Jupiter: ["10♠","6♦","A♣","J♣","9♥","K♦","Q♣"],
        Saturn: ["7♦","10♥","4♠","2♦","9♠","6♣","4♥"],
        Uranus: ["J♥","5♠","3♦","Q♥","7♣","5♥","4♦"],
        Neptune: ["2♣","Q♠","6♥","9♦","8♣","A♥","K♣"]
      },
      emblem: "A♠ (Mercury line, seat 2)"
    },
    planets: {
      Mercury: "Power to control and carry on profession or labor. Rapid accomplishment of work. Overcoming of an obstacle. Ability to succeed against antagonistic circumstances.",
      Venus: "Power in overcoming obstacles. Female power and strength of will. A labor of love. Female organizations. Meetings of females for purposes of work in some cause.",
      Mars: "Organizations of males. Power gained through concentration of forces. Development of power. Overcoming of obstacles.",
      Jupiter: "Power represented by organizations such as manufacturing companies, railroad corporations and labor organizations. Power and strength in numbers.",
      Saturn: "Power in overcoming illness and obstacles to advancement. Recovery from illness, when such exists at the time of the delineating.",
      Uranus: "Strength and power in professional or other labor. Ability to overcome all obstacles. Organized labor. Concentration of forces.",
      Neptune: "Travel that affects numbers of people and business interests at a distance. Concentrated effort at a distance. Control of laborers in large numbers."
    } },
  "9_spades": { name: "Nine of Spades", solar: 48, spirit: 35, astral: "12772",
    spread: {
      sun: ["10♥","9♠","9♦"],
      lines: {
        Mercury: ["8♣","8♠","J♥","5♠","3♦","Q♥","7♣"],
        Venus: ["5♥","4♦","2♣","Q♠","8♥","A♠","6♥"],
        Mars: ["5♦","3♣","A♥","7♥","10♦","K♣","2♥"],
        Jupiter: ["J♠","6♠","A♦","J♦","9♣","3♥","Q♦"],
        Saturn: ["7♠","10♣","K♥","2♠","10♠","6♦","4♣"],
        Uranus: ["J♣","9♥","3♠","Q♣","7♦","5♣","4♠"],
        Neptune: ["2♦","K♠","6♣","4♥","8♦","A♣","K♦"]
      },
      emblem: "A♠ (Venus line, seat 6)"
    },
    planets: {
      Mercury: "Sudden illness or an accident. Injury to some person. A bitter disappointment, but one that will soon pass. Dissatisfaction with labor.",
      Venus: "Illness caused by powerful emotions. Illness of a lady friend, or relative by marriage. A disappointment of a wish or aspiration to succeed.",
      Mars: "A lawsuit. Disappointment caused by a man. Ill success in some undertaking. Loss caused through illness. In some cases a secret disclosure.",
      Jupiter: "Financial loss, disappointment, trouble, failure, bankruptcy, default of employee and kindred troubles, according to other indications in same lay-out.",
      Saturn: "An illness of self, or a near friend. If with 7 s, it indicates a fatal termination. If near your birth card, it warns you to be extremely careful of yourself.",
      Uranus: "Disappointment in one's labor. A disagreeable labor performed. A disappointing occurrence at a distance. A missed opportunity. Disappointment in a real estate deal.",
      Neptune: "An accident by water. Illness caused by dampness. Disappointment regarding a journey. Bad news from a distance."
    } },
  "10_spades": { name: "Ten of Spades", solar: 49, spirit: 45, astral: "65413",
    spread: {
      sun: ["10♣","10♠","4♥"],
      lines: {
        Mercury: ["8♦","9♠","J♣","9♥","3♠","Q♣","7♦"],
        Venus: ["5♣","4♠","2♦","K♠","8♣","8♠","6♣"],
        Mars: ["5♠","3♦","A♣","7♣","5♥","K♦","2♣"],
        Jupiter: ["Q♠","10♥","A♠","6♥","9♦","3♣","A♥"],
        Saturn: ["J♥","10♦","K♣","Q♥","J♠","6♠","4♦"],
        Uranus: ["J♦","9♣","8♥","Q♦","7♠","5♦","K♥"],
        Neptune: ["2♠","7♥","6♦","4♣","2♥","A♦","3♥"]
      },
      emblem: "A♠ (Jupiter line, seat 3)"
    },
    planets: {
      Mercury: "Successful labor. A quick return for labor performed. Professional success. Success in a speculation. Success in a business connected with rapid transportation.",
      Venus: "Success and happiness in one's labor, home life and general surroundings. Indications especially strong for females. Success in business where females are largely employed.",
      Mars: "Strength to bear trouble and to labor for some great good. General success, especially for males. In some cases predicts success in a lawsuit.",
      Jupiter: "General pecuniary success in mercantile pursuits, professional undertakings, and manufacturing enterprises. A strong card under Jupiter.",
      Saturn: "Success in the practice of medicine, healing and kindred pursuits. Indicates recovery from illness when such is shown elsewhere. Counteracts the nine of spades.",
      Uranus: "Good and increasing success in all pursuits connected with labor. Success in real estate transactions. Overcoming of troubles.",
      Neptune: "Success in pursuit of various kinds connected with travel, especially with the water. Fishing, boating and travel by water."
    } },
  "J_spades": { name: "Jack of Spades", solar: 50, spirit: 55, astral: "26666",
    spread: {
      sun: ["10♦","J♠","4♣"],
      lines: {
        Mercury: ["2♥","10♠","J♦","9♣","8♥","Q♦","7♠"],
        Venus: ["5♦","K♥","2♠","7♥","8♦","9♠","6♦"],
        Mars: ["9♥","3♠","A♦","7♦","5♣","3♥","2♦"],
        Jupiter: ["K♠","10♣","8♠","6♣","4♥","3♦","A♣"],
        Saturn: ["J♣","5♥","K♦","Q♣","Q♠","10♥","4♠"],
        Uranus: ["6♥","9♦","8♣","A♥","J♥","5♠","K♣"],
        Neptune: ["Q♥","7♣","6♠","4♦","2♣","A♠","3♣"]
      },
      emblem: "A♠ (Neptune line, seat 6)"
    },
    planets: {
      Mercury: "An industrious young man. A man who is engaged in some line of work requiring quickness and skill. A successful man in most cases.",
      Venus: "An industrious man who is engaged in some occupation that is clean and light, requiring keen perceptions and ability to make and keep friends.",
      Mars: "A gentleman connected with the law. or some trade requiring strong will force and power, or, in some cases, manly strength.",
      Jupiter: "An active young man, engaged in some mercantile or professional pursuit. A powerful worker. Steady and industrious.",
      Saturn: "A young or middle aged man engaged in some pursuit connected with medicine, such as a physician, druggist, or something of the kind.",
      Uranus: "A hard-working young or middle aged man. In some cases a dealer in real estate. In some aspects indicates a farmer or laborer.",
      Neptune: "Usually indicates a sailor, or one connected with water transportation; but may also represent a traveling salesman or tradesman."
    } },
  "Q_spades": { name: "Queen of Spades", solar: 51, spirit: 65, astral: "44576",
    spread: {
      sun: ["5♥","Q♠","4♦"],
      lines: {
        Mercury: ["2♣","J♠","6♥","9♦","8♣","A♥","J♥"],
        Venus: ["5♠","K♣","Q♥","7♣","2♥","10♠","6♠"],
        Mars: ["9♣","8♥","A♠","7♠","5♦","3♣","2♠"],
        Jupiter: ["7♥","10♦","9♠","6♦","4♣","3♠","A♦"],
        Saturn: ["J♦","5♣","3♥","Q♦","K♠","10♣","K♥"],
        Uranus: ["6♣","4♥","8♦","A♣","J♣","9♥","K♦"],
        Neptune: ["Q♣","7♦","10♥","4♠","2♦","8♠","3♦"]
      },
      emblem: "A♠ (Mars line, seat 3)"
    },
    planets: {
      Mercury: "An industrious lady, who is quick of motion and hurries about her work. Generally quite nervous in temperament.",
      Venus: "An affectionate, faithful and industrious wife and mother. In some cases, however, it indicates a single lady of same disposition.",
      Mars: "A hard-working woman, inclined to a masculine bearing. Sometimes shows a quarrelsome woman and one who talks against her neighbors.",
      Jupiter: "A business lady. One who loves to transact business and to handle money. In some cases one who is employed in a mercantile institution.",
      Saturn: "Sometimes indicates a female physician. A lady who is ill. A lady employed in some place where the sick are treated.",
      Uranus: "A hard-working woman, who delights in running things. She cannot bear to see a speck of dirt about the house. Kindly disposition.",
      Neptune: "A lady who is a worker in some line affecting or connected with travel. In some cases the wife of a man who travels. A traveled lady, a worker."
    } },
  "K_spades": { name: "King of Spades", solar: 52, spirit: 75, astral: "44585",
    spread: {
      sun: ["5♣","K♠","4♠"],
      lines: {
        Mercury: ["2♦","Q♠","6♣","4♥","8♦","A♣","J♣"],
        Venus: ["9♥","K♦","Q♣","7♦","2♣","J♠","10♥"],
        Mars: ["9♦","8♣","8♠","J♥","5♠","3♦","Q♥"],
        Jupiter: ["7♣","5♥","10♠","6♠","4♦","8♥","A♠"],
        Saturn: ["6♥","5♦","3♣","A♥","7♥","10♦","K♣"],
        Uranus: ["6♦","4♣","2♥","A♦","J♦","9♣","3♥"],
        Neptune: ["Q♦","7♠","10♣","K♥","2♠","9♠","3♠"]
      },
      emblem: "A♠ (Jupiter line, seat 7)"
    },
    planets: {
      Mercury: "A quick-tempered, hard-working, rushing man. One who employs many workmen, in some cases. An energetic business man.",
      Venus: "A man of kindly disposition, not very wealthy, usually one who is a hard worker. Kind to his family. In some cases the head of a concern employing females.",
      Mars: "Usually denotes an industrious, professional gentleman. An attorney at law, a judge, or some office holder. In some cases, the head of a concern employing male help.",
      Jupiter: "A manufacturer or a gentleman who employs a great deal of labor. A self-made man. A man of influence. A business rusher.",
      Saturn: "An old and experienced physician. In some cases a hardworked man who has bad health. Usually represents an over-worked person.",
      Uranus: "A sober, industrious, business man who carries on a business that employs others. A controller of labor. A real estate dealer.",
      Neptune: "A gentleman connected with travel and transportation. In some cases an officer, a captain of a vessel or a superintendent of some company employed in water traffic."
    } },
};
