// yearcarddata.js — original Sage-voice yearly-card readings for mysticscards.space.
//
// Your Yearly card is the card ruling your current age-year, read under one of
// the seven planets (SPREAD_PLANETS[age % 7]). So each card carries one reading
// per planet, written for the whole twelve-month arc — the longest of the three
// horizons (compare js/dailycarddata.js for the day and js/periodcarddata.js for
// the 52-day period). Same register: name the card's Cardology identity, bring in
// the year's ruling planet and show how it colours the twelve months, then close
// on an orientation for the year.
//
// NOT yet wired into any page or sw.js — prepared for future use.
//
// key = `${rank}_${suit}` (matches CARDS / RICHMOND); planets = Mercury..Neptune.
window.YEAR_CARDS = {
  "A_hearts": { name: "Ace of Hearts", planets: {
    Mercury: "The Ace of Hearts is the card of the open heart, desire taking its first breath. A Mercury year carries the affection through words and connection over the twelve months ahead, love that grows by conversation and the keeping in touch. Across the year, speak the warm thing often, the bond is built in steady contact.",
    Venus: "The Ace of Hearts is the card of the open heart, love at its first spark. A Venus year is the most favored of all for the heart, a whole stretch tilted toward new affection and warmth. Let the year open you, this is a season of beginnings worth saying yes to.",
    Mars: "The Ace of Hearts is the card of the open heart, desire newly lit. A Mars year drives the wanting toward action across the twelve months, a love pursued rather than waited for. Move on what you feel this year, and let the ardor build something lasting rather than flare and fade.",
    Jupiter: "The Ace of Hearts is the card of the open heart, the first warmth of wanting. A Jupiter year widens the affection into abundance over the months ahead, a heart that gives freely and is repaid in kind. Spend the year generous with warmth, what you offer comes back enlarged.",
    Saturn: "The Ace of Hearts is the card of the open heart, fresh desire reaching out. A Saturn year asks the longing to be patient across the twelve months, a love that must be earned or waited for. Hold the feeling steady through the year, what you build slowly here will hold.",
    Uranus: "The Ace of Hearts is the card of the open heart, desire arriving unannounced. A Uranus year makes the affection of these twelve months sudden and unpredictable, a connection from a direction you never planned. Stay open all year, the unexpected one is worth following.",
    Neptune: "The Ace of Hearts is the card of the open heart, longing in its purest form. A Neptune year turns the heart toward the far and the unseen over the months ahead, a love at a distance or an ideal more dreamed than held. Let the longing deepen this year, and keep your feet on the ground as you reach."
  } },
  "2_hearts": { name: "Two of Hearts", planets: {
    Mercury: "The Two of Hearts is the card of union, two drawn into one. A Mercury year builds the bond through talk over the twelve months, a closeness deepened by conversation, plans, and constant exchange. Keep the words honest all year, this union is made and remade in what you say.",
    Venus: "The Two of Hearts is the card of union, the meeting of hearts. A Venus year blesses partnership above all, the most favored stretch for love and deep friendship to take root. Show up open across the year, a true union is genuinely available now.",
    Mars: "The Two of Hearts is the card of union, two bound close. A Mars year runs the relationship hot over the twelve months, passion and friction both stronger than usual. Move through the year's sparks without wreckage, the bond beneath holds when you tend it.",
    Jupiter: "The Two of Hearts is the card of union, the joining of two. A Jupiter year enriches the bond over the months ahead, a relationship that grows by being shared and opened outward. Widen the circle this year, the good multiplies when you stop keeping it small.",
    Saturn: "The Two of Hearts is the card of union, two held together. A Saturn year tests the tie across the twelve months, with duty, distance, or the plain weight of time. Tend it faithfully through the year, the bond that survives this stretch is the sound and lasting one.",
    Uranus: "The Two of Hearts is the card of union, two made one. A Uranus year makes the relationships of these months sudden and changeable, an abrupt closeness or an unexpected turn in an old bond. Trust the year's changes, the unplanned pairing runs on its own true logic.",
    Neptune: "The Two of Hearts is the card of union, the bond between two. A Neptune year stretches the tie across distance over the twelve months, a love held over miles or a reunion long in coming. Trust the thread all year, it holds over any gap."
  } },
  "3_hearts": { name: "Three of Hearts", planets: {
    Mercury: "The Three of Hearts is the card of the divided heart, feeling that runs more directions than one. A Mercury year fills the twelve months with the mind's noise about the heart, options weighed and reweighed. Across the year, stop tallying and sit with the truth, the answer is quieter than the worry.",
    Venus: "The Three of Hearts is the card of the divided heart, affection pulled more than one way. A Venus year sweetens the year's confusion, more than one love or pleasure looking good at once. Over the months ahead, choose what steadies you rather than what merely charms.",
    Mars: "The Three of Hearts is the card of the divided heart, want split against itself. A Mars year turns the division to friction across the twelve months, tension with others or inside your own chest. Pick a direction early in the year and the strain drains out of the months.",
    Jupiter: "The Three of Hearts is the card of the divided heart, feeling in abundance. A Jupiter year floods the twelve months with more emotion than you can spend. Pour the surplus into making something across the year, the feeling is looking for a form.",
    Saturn: "The Three of Hearts is the card of the divided heart, torn between two goods. A Saturn year hardens the indecision into a long worry over the months ahead. Name the fear plainly and early, and the year loses the anxious loop it would otherwise circle.",
    Uranus: "The Three of Hearts is the card of the divided heart, certainty split open. A Uranus year brings the unexpected feeling across the twelve months, the one that scrambles your settled mind. Let it disturb the year, it points at a truer want than the one you planned.",
    Neptune: "The Three of Hearts is the card of the divided heart, longing in two places at once. A Neptune year stretches the months between here and somewhere far. Let the division stay open across the year, not every split needs settling inside it."
  } },
  "4_hearts": { name: "Four of Hearts", planets: {
    Mercury: "The Four of Hearts is the card of the settled heart, love with a roof and a hearth. A Mercury year fills the twelve months with the small business of home, the arrangements and news that settle a household. Across the year, attend to the domestic details, the peace here is built in the ordinary.",
    Venus: "The Four of Hearts is the card of the settled heart, contentment in a warm room. A Venus year makes the whole stretch easy and homelike, love resting on familiar ground. Be fully in the comfort over the months, this is a year to enjoy what you have built.",
    Mars: "The Four of Hearts is the card of the settled heart, the secure home. A Mars year pushes against the peace across the twelve months, something testing the quiet you made. Defend the calm through the year without letting the guarding harden into a standing war.",
    Jupiter: "The Four of Hearts is the card of the settled heart, the full house. A Jupiter year widens the home over the months ahead, more comfort, more company, more room at the table. Enjoy the plenty this year, and let others come and sit inside it with you.",
    Saturn: "The Four of Hearts is the card of the settled heart, the foundation. A Saturn year tests the home's footing across the twelve months, pressing on what you have built. What was made true will stand the year, so shore up the rest without panic.",
    Uranus: "The Four of Hearts is the card of the settled heart, the steady home. A Uranus year reaches change into the settled place over the months, a shift in where or how you live. Let the walls breathe this year, a security that cannot bend is already cracking.",
    Neptune: "The Four of Hearts is the card of the settled heart, the longing to belong. A Neptune year fills the twelve months with a homesickness or a hunger for the hearth somewhere you are not. Carry the warmth within you across the year until you reach what holds it."
  } },
  "5_hearts": { name: "Five of Hearts", planets: {
    Mercury: "The Five of Hearts is the card of the restless heart, love that itches for new air. A Mercury year scatters the twelve months into restless thoughts and half-plans. Let the ideas move across the year, but do not mistake the itch for a real instruction.",
    Venus: "The Five of Hearts is the card of the restless heart, affection hungry for newness. A Venus year makes the familiar feel small over the months and the new feel bright. Follow the warmth this year if you must, without burning a good thing for the sake of motion.",
    Mars: "The Five of Hearts is the card of the restless heart, feeling that wants out. A Mars year charges the twelve months with a surge that needs somewhere to go. Spend the restlessness in real change across the year, the heart wants genuine movement.",
    Jupiter: "The Five of Hearts is the card of the restless heart, change in love. A Jupiter year opens a wider field over the months ahead, more room for affection than you stand in now. Step into it generously this year, there is more here than you fear losing.",
    Saturn: "The Five of Hearts is the card of the restless heart, the wish to bolt. A Saturn year sets a wall across the twelve months, a leaving you cannot make yet. Stay put through the year, the restlessness is showing you where you actually want to go.",
    Uranus: "The Five of Hearts is the card of the restless heart, the urge to break the pattern. A Uranus year disrupts the twelve months with something genuinely new. Let the year break the rut, the stale arrangement was overdue to come loose.",
    Neptune: "The Five of Hearts is the card of the restless heart, the pull toward elsewhere. A Neptune year fills the months with longing for water and open distance. Let the daydream run across the year, then ask what it is really hungry for."
  } },
  "6_hearts": { name: "Six of Hearts", planets: {
    Mercury: "The Six of Hearts is the card of the peacemaking heart, love that balances its own books. A Mercury year circles old matters back across the twelve months for a word and a settling. Answer them squarely through the year, balance is the whole of what is asked.",
    Venus: "The Six of Hearts is the card of the peacemaking heart, feeling returned to its level. A Venus year brings love back to fairness over the months, even and unforced. Give what you owe the heart across the year, and harmony settles in on its own.",
    Mars: "The Six of Hearts is the card of the peacemaking heart, the debt of feeling. A Mars year presses an emotional account to be paid across the twelve months. Meet it with steadiness through the year rather than heat, and the books come clear.",
    Jupiter: "The Six of Hearts is the card of the peacemaking heart, fair return. A Jupiter year brings back over the months what you once gave in love, enriched. Receive it without protest this year, the earlier kindness has come around.",
    Saturn: "The Six of Hearts is the card of the peacemaking heart, the responsibility you carry. A Saturn year fixes an emotional duty to your shoulders across the twelve months. Carry it well through the year, this is the weight that makes you someone others can trust.",
    Uranus: "The Six of Hearts is the card of the peacemaking heart, fate squaring accounts. A Uranus year rearranges over the months what you thought was fixed in the heart. Let it happen across the year, the sudden change is balancing something overdue.",
    Neptune: "The Six of Hearts is the card of the peacemaking heart, justice across distance. A Neptune year brings something long owed quietly due over the twelve months. Trust the slow fairness of the year, what is owed finds its way home without forcing."
  } },
  "7_hearts": { name: "Seven of Hearts", planets: {
    Mercury: "The Seven of Hearts is the card of the testing heart, love asked to hold without gripping. A Mercury year lets doubt talk loudly across the twelve months. Hear it out through the year, then keep faith with what your heart already knows.",
    Venus: "The Seven of Hearts is the card of the testing heart, affection without grasping. A Venus year asks you to give freely over the months and hold nothing by force. Loosen the grip across the year, what stays of its own will was never yours to clutch.",
    Mars: "The Seven of Hearts is the card of the testing heart, the struggle you cannot win by force. A Mars year offers a fight across the twelve months that fighting only worsens. Yield the small battles through the year to keep the larger peace.",
    Jupiter: "The Seven of Hearts is the card of the testing heart, faith over worry. A Jupiter year rewards over the months the trust that fear called foolish. Lean into the warmth across the year, and the dread shrinks as the months prove it small.",
    Saturn: "The Seven of Hearts is the card of the testing heart, endurance. A Saturn year sets a heaviness on the heart across the twelve months, a weight to be borne. Carry it without bitterness through the year, it lifts sooner than it feels from inside.",
    Uranus: "The Seven of Hearts is the card of the testing heart, the grip suddenly loosened. A Uranus year frees you over the months from a love you clutched too hard. Let it go open-handed across the year, what leaves freely makes room for what comes.",
    Neptune: "The Seven of Hearts is the card of the testing heart, faith more than fact. A Neptune year has you reaching across the twelve months for something you cannot quite hold. Rest in the not-knowing through the year, you are held even where the floor is unseen."
  } },
  "8_hearts": { name: "Eight of Hearts", planets: {
    Mercury: "The Eight of Hearts is the card of the magnetic heart, warmth with real power in it. A Mercury year puts that pull into your words across the twelve months, a charm that moves people. Use it to mend rather than to win all year.",
    Venus: "The Eight of Hearts is the card of the magnetic heart, an easy and bright pull. A Venus year raises your magnetism over the months, others drawn near without effort. Wield it gently across the year, power in love is meant to heal.",
    Mars: "The Eight of Hearts is the card of the magnetic heart, the force of feeling. A Mars year wants that power to command across the twelve months. Lead with the heart's strength through the year, and never once use it to overpower.",
    Jupiter: "The Eight of Hearts is the card of the magnetic heart, warmth that opens doors. A Jupiter year widens your influence over the months, hands and doors swinging open. Give generously across the year, the more you spend the larger it grows.",
    Saturn: "The Eight of Hearts is the card of the magnetic heart, strength put to work. A Saturn year asks your power to feel to steady someone's pain across the twelve months. Stand firm for them through the year, this is what the strength is for.",
    Uranus: "The Eight of Hearts is the card of the magnetic heart, sudden charisma. A Uranus year surprises you over the months with a pull that arrives from nowhere. Let it move through cleanly across the year, do not grip it and do not perform it.",
    Neptune: "The Eight of Hearts is the card of the magnetic heart, warmth that travels. A Neptune year sends your pull past the room across the twelve months, to those at a distance who feel you. Send the warmth out all year, it lands where it is needed."
  } },
  "9_hearts": { name: "Nine of Hearts", planets: {
    Mercury: "The Nine of Hearts is the card of the wide heart, love grown large enough to give away. A Mercury year brings word across the twelve months that closes a chapter of feeling. Read it without clinging through the year, a completion is its own kind of gift.",
    Venus: "The Nine of Hearts is the card of the wide heart, love come full. A Venus year asks the fullness to be given away over the months, not hoarded. Hold the many in that wide warmth across the year, this is the most generous of stretches.",
    Mars: "The Nine of Hearts is the card of the wide heart, the ending that frees. A Mars year demands across the twelve months that you release your grip on something already leaving. Open the hand through the year, what fights to stay was halfway gone.",
    Jupiter: "The Nine of Hearts is the card of the wide heart, overflow. A Jupiter year sends fulfillment past the brim over the months. Spend the abundance on the many across the year, it was never meant to be only yours.",
    Saturn: "The Nine of Hearts is the card of the wide heart, the graceful loss. A Saturn year asks you to let something go cleanly across the twelve months. Grieve it honestly through the year, and feel how much room the releasing makes.",
    Uranus: "The Nine of Hearts is the card of the wide heart, sudden completion. A Uranus year frees you over the months from something you held far too long. Let the surprise land across the year, your hands are lighter than they were.",
    Neptune: "The Nine of Hearts is the card of the wide heart, the small self dissolving into a larger love. A Neptune year softens your boundaries across the twelve months. Let them blur through the year, you lose nothing by belonging to more than yourself."
  } },
  "10_hearts": { name: "Ten of Hearts", planets: {
    Mercury: "The Ten of Hearts is the card of the crowded heart, love that arrives in numbers. A Mercury year turns many voices warm toward you across the twelve months. Take the goodwill in through the year, and keep returning the gracious word.",
    Venus: "The Ten of Hearts is the card of the crowded heart, affection in company. A Venus year fills the months with welcome and the warmth of a crowd. Stand inside it across the year and let yourself simply be glad to be among them.",
    Mars: "The Ten of Hearts is the card of the crowded heart, the wish to win the room. A Mars year sharpens that drive across the twelve months, the urge to shine for the many. Lead the gatherings with warmth through the year, and let no one be trampled by your light.",
    Jupiter: "The Ten of Hearts is the card of the crowded heart, affection multiplied. A Jupiter year sends love back to you through many hands over the months. Receive the plenty across the year of being widely cared for, and pass the glow along.",
    Saturn: "The Ten of Hearts is the card of the crowded heart, public warmth. A Saturn year lays a quiet duty under the recognition across the twelve months. Wear the regard lightly through the year, and keep your deeper faith with the few.",
    Uranus: "The Ten of Hearts is the card of the crowded heart, sudden belonging. A Uranus year drops you over the months into a circle of unexpected people. Step into it across the year, the gathering formed around you for a reason.",
    Neptune: "The Ten of Hearts is the card of the crowded heart, love from afar. A Neptune year brings warmth across the twelve months from many you may never meet. Feel the wide tide of it all year and let it lift you where you stand."
  } },
  "J_hearts": { name: "Jack of Hearts", planets: {
    Mercury: "The Jack of Hearts is the card of the devoted heart, the youth who gives himself wholly. A Mercury year quickens bright young thoughts of love across the twelve months. Speak them with plain sincerity through the year, the cleverness can wait its turn.",
    Venus: "The Jack of Hearts is the card of the devoted heart, eager to give itself away. A Venus year raises that devotion over the months, warm and unguarded. Offer it freely across the year, and keep just enough of the warmth for yourself.",
    Mars: "The Jack of Hearts is the card of the devoted heart, ardor wanting to prove itself. A Mars year fires across the twelve months the urge to show your feeling in action. Let the courage serve someone real through the year, not only your own pride.",
    Jupiter: "The Jack of Hearts is the card of the devoted heart, generosity young and wide. A Jupiter year opens your giving fully over the months. Give with both hands across the year, the well refills faster than you can pour.",
    Saturn: "The Jack of Hearts is the card of the devoted heart, devotion asked to cost something. A Saturn year calls for a real sacrifice across the twelve months. Give it willingly through the year, and let no resentment salt the gift.",
    Uranus: "The Jack of Hearts is the card of the devoted heart, ardor that breaks composure. A Uranus year cracks your careful surface open over the months. Let the freshness through across the year, it is more honest than the caution it overran.",
    Neptune: "The Jack of Hearts is the card of the devoted heart, love offered to the unseen. A Neptune year points your devotion across the twelve months toward something far and beyond sight. Follow it through the year, the heart knows where it means to kneel."
  } },
  "Q_hearts": { name: "Queen of Hearts", planets: {
    Mercury: "The Queen of Hearts is the card of the mothering heart, care that holds and warms. A Mercury year puts gentle steadying words in your mouth across the twelve months. Speak them plainly and kindly through the year, the way the mother in you knows how.",
    Venus: "The Queen of Hearts is the card of the mothering heart, love flowing as care. A Venus year moves that tenderness toward others all year long. Nurture freely across the months, and let yourself be tended in your turn.",
    Mars: "The Queen of Hearts is the card of the mothering heart, warmth turned fierce. A Mars year asks your care to fight for someone across the twelve months. Protect them through the year, and keep the fierceness clean of cruelty.",
    Jupiter: "The Queen of Hearts is the card of the mothering heart, care that widens. A Jupiter year stretches your capacity over the months to hold more than usual. Open your arms wide across the year, there is plenty of you to go around.",
    Saturn: "The Queen of Hearts is the card of the mothering heart, the one leaned on. A Saturn year sets others' needs against your strength across the twelve months. Hold steady through the year, and set the boundary that keeps your own giving whole.",
    Uranus: "The Queen of Hearts is the card of the mothering heart, care called into a new shape. A Uranus year brings sudden needs over the months that no routine fits. Answer them freshly across the year, love is not a fixed procedure.",
    Neptune: "The Queen of Hearts is the card of the mothering heart, tenderness that reaches far. A Neptune year sends your care across the twelve months toward the distant and the unseen in need. Send it out through the year, it crosses the distance and arrives."
  } },
  "K_hearts": { name: "King of Hearts", planets: {
    Mercury: "The King of Hearts is the card of the mastered heart, the one who rules by warmth. A Mercury year hands you the words that settle heated rooms across the twelve months. Speak from the calm center through the year, and others find theirs in it.",
    Venus: "The King of Hearts is the card of the mastered heart, love held in a sure hand. A Venus year steadies your leading all year, warm and even. Be the safety others rest in across the months, that is the whole of the authority.",
    Mars: "The King of Hearts is the card of the mastered heart, feeling and command at odds. A Mars year pulls the two against each other across the twelve months. Rule the heat with the heart through the year, command without conquering.",
    Jupiter: "The King of Hearts is the card of the mastered heart, generosity that leads. A Jupiter year lays the weight of leadership on your giving over the months. Give well across the year, and let your abundance set the standard for the rest.",
    Saturn: "The King of Hearts is the card of the mastered heart, mastery under load. A Saturn year tests it across the twelve months with a heavy duty of care. Carry it without going cold through the year, the strength is meant to stay warm.",
    Uranus: "The King of Hearts is the card of the mastered heart, steadiness meeting change. A Uranus year asks the master to adapt across the months without losing center. Bend through the year, stay rooted, and lead the disruption with a gentle hand.",
    Neptune: "The King of Hearts is the card of the mastered heart, authority that reaches far. A Neptune year extends your steadiness across the twelve months to those who are distant. Trust the long reach of your calm all year, it holds them out of sight."
  } },
  "A_clubs": { name: "Ace of Clubs", planets: {
    Mercury: "The Ace of Clubs is the card of the hungry mind, the thirst to know. A Mercury year doubles the spark across the twelve months, a whole stretch made for study, questions, and learning. Chase the curiosity through the year, your mind is lit for a reason.",
    Venus: "The Ace of Clubs is the card of the hungry mind, curiosity newly lit. A Venus year turns the year's learning toward beauty, a fascination pursued for pleasure. Study what delights you across the months, not every inquiry needs a use.",
    Mars: "The Ace of Clubs is the card of the hungry mind, the first reach for knowing. A Mars year drives the inquiry hard over the twelve months, a need to get to the bottom of things. Pursue the answers through the year, but do not mistake speed for understanding.",
    Jupiter: "The Ace of Clubs is the card of the hungry mind, fresh curiosity. A Jupiter year widens the field over the months, more to learn than you can hold. Follow the broadest threads across the year, the abundance of it is the gift.",
    Saturn: "The Ace of Clubs is the card of the hungry mind, a question newly formed. A Saturn year meets it with patience across the twelve months, answers that come only by slow work. Sit with the not-knowing through the year, the discipline of waiting is its own study.",
    Uranus: "The Ace of Clubs is the card of the hungry mind, curiosity arriving from nowhere. A Uranus year sparks sudden ideas over the months, flashes that reorder what you knew. Catch them across the year, the strange thought is the true one.",
    Neptune: "The Ace of Clubs is the card of the hungry mind, the reach toward what is hidden. A Neptune year points the year's questions at the unseen, the mystery behind the plain fact. Let the not-knowing stay open across the months, some answers arrive only sideways."
  } },
  "2_clubs": { name: "Two of Clubs", planets: {
    Mercury: "The Two of Clubs is the card of the meeting of minds, ideas passed between two. A Mercury year runs straight through the twelve months, conversations that spark and build. Speak and listen in equal measure across the year, the best ideas are the shared ones.",
    Venus: "The Two of Clubs is the card of the meeting of minds, thought shared in warmth. A Venus year sweetens the year's exchanges, understanding that feels like affection. Keep the talk kind across the months, agreement comes easier than you fear.",
    Mars: "The Two of Clubs is the card of the meeting of minds, two ideas in the room. A Mars year turns the year's exchanges to debate, views clashing with heat. Argue the point and not the person across the months, and let the better idea win.",
    Jupiter: "The Two of Clubs is the card of the meeting of minds, thought made larger by sharing. A Jupiter year widens the conversation over the twelve months, more voices and more ground. Bring others in across the year, the idea grows the moment you stop holding it alone.",
    Saturn: "The Two of Clubs is the card of the meeting of minds, an exchange that must be earned. A Saturn year slows the talk over the months, misunderstandings that take patience to clear. Stay at the table through the year, say it again carefully, and the gap closes.",
    Uranus: "The Two of Clubs is the card of the meeting of minds, two thoughts striking light. A Uranus year makes the year's meetings sudden, ideas arriving whole from unexpected exchanges. Follow the sparks across the months, the unplanned conversation is the one that matters.",
    Neptune: "The Two of Clubs is the card of the meeting of minds, understanding across distance. A Neptune year carries the exchange far over the twelve months, thought meeting thought with someone away. Trust the connection through the year, minds reach each other over any gap."
  } },
  "3_clubs": { name: "Three of Clubs", planets: {
    Mercury: "The Three of Clubs is the card of the restless mind, more ideas than one head can settle. A Mercury year scatters the twelve months into thoughts firing every direction. Across the year, stop chasing all of them, choose the one that matters and let the rest go quiet.",
    Venus: "The Three of Clubs is the card of the restless mind, thought pulled many ways. A Venus year makes several options look pleasant over the months, none clearly best. Across the year, choose the idea that brings real ease over the one that merely charms.",
    Mars: "The Three of Clubs is the card of the restless mind, ideas at war with each other. A Mars year turns the noise to friction across the twelve months, worry that picks fights inside you. Settle on one course early in the year and the quarrel quiets.",
    Jupiter: "The Three of Clubs is the card of the restless mind, ideas in surplus. A Jupiter year sends more than you can use over the months, an overflow of plans. Pour the extra into making something across the year, the surplus wants a shape.",
    Saturn: "The Three of Clubs is the card of the restless mind, worry that circles. A Saturn year hardens the indecision across the twelve months, the same anxious loop tightening. Write the fear down plainly through the year, and the spiral loses its power.",
    Uranus: "The Three of Clubs is the card of the restless mind, certainty scattered. A Uranus year throws the unexpected thought over the months, the one that upends your plan. Let it land across the year, the disruption points at a better question.",
    Neptune: "The Three of Clubs is the card of the restless mind, thought split between here and far. A Neptune year pulls your attention across the twelve months toward the distant and dreamed. Let the wandering be through the year, not every loose idea needs catching."
  } },
  "4_clubs": { name: "Four of Clubs", planets: {
    Mercury: "The Four of Clubs is the card of the settled mind, knowledge that holds. A Mercury year brings word across the twelve months that confirms what you suspected. Take the certainty in through the year, and let your thinking rest on it.",
    Venus: "The Four of Clubs is the card of the settled mind, the comfort of knowing. A Venus year makes the year's certainty pleasant, a belief that feels like home. Enjoy the steadiness across the months, you have earned the right to be sure.",
    Mars: "The Four of Clubs is the card of the settled mind, a conviction held firm. A Mars year sends challenges to it over the twelve months. Defend the truth calmly through the year, without turning the defense into a brawl.",
    Jupiter: "The Four of Clubs is the card of the settled mind, sound knowledge. A Jupiter year widens it over the months, your understanding stretching to cover more. Build on the firm ground across the year, the foundation will carry the weight.",
    Saturn: "The Four of Clubs is the card of the settled mind, the foundation of thought. A Saturn year tests that base across the twelve months, pressing on what you believe. What is true will hold the year, so let the rest be questioned without fear.",
    Uranus: "The Four of Clubs is the card of the settled mind, a fixed certainty. A Uranus year cracks it open over the months, new facts unsettling old belief. Let the conviction loosen across the year, a mind that cannot change is already wrong.",
    Neptune: "The Four of Clubs is the card of the settled mind, knowledge at rest. A Neptune year blurs the edges across the twelve months, certainty softening toward mystery. Hold what you know lightly through the year, the deeper truth is rarely fixed."
  } },
  "5_clubs": { name: "Five of Clubs", planets: {
    Mercury: "The Five of Clubs is the card of the roaming mind, curiosity that will not sit still. A Mercury year speeds the wandering across the twelve months, thoughts darting one to the next. Let them roam through the year, but pin down the one worth keeping.",
    Venus: "The Five of Clubs is the card of the roaming mind, attention hungry for the new. A Venus year makes the familiar dull over the months and the novel bright. Chase the new idea across the year if you like, without abandoning the good one half-finished.",
    Mars: "The Five of Clubs is the card of the roaming mind, thought that wants out. A Mars year charges the restlessness across the twelve months, mental energy needing a target. Aim it at one real problem through the year and let it burn there.",
    Jupiter: "The Five of Clubs is the card of the roaming mind, curiosity widening. A Jupiter year opens new ground over the months, more to explore than before. Wander generously across the year, there is more to learn than you risk by moving.",
    Saturn: "The Five of Clubs is the card of the roaming mind, the wish to think of anything else. A Saturn year sets a dull but necessary task before you across the twelve months. Stay with it through the year, the focus you resist is exactly the one you need.",
    Uranus: "The Five of Clubs is the card of the roaming mind, the urge to break routine. A Uranus year scatters your settled thinking over the months with something new. Let it disrupt the year, the stale mental groove was overdue to break.",
    Neptune: "The Five of Clubs is the card of the roaming mind, thought drifting toward the far. A Neptune year fills the twelve months with wandering, ideas of elsewhere and otherwise. Let the drift run through the year, then ask what it is really searching for."
  } },
  "6_clubs": { name: "Six of Clubs", planets: {
    Mercury: "The Six of Clubs is the card of the responsible mind, the messenger who must be true. A Mercury year hands you weighty words across the twelve months, messages that matter. Say them accurately and kindly through the year, the responsibility is in the telling.",
    Venus: "The Six of Clubs is the card of the responsible mind, thought returned to fairness. A Venus year evens your judgment over the months, a chance to set a mental score straight. Speak the balanced word across the year, and let an old misunderstanding rest.",
    Mars: "The Six of Clubs is the card of the responsible mind, a duty of truth. A Mars year presses you across the twelve months to say the hard thing. Deliver it with steadiness through the year rather than heat, and the air clears.",
    Jupiter: "The Six of Clubs is the card of the responsible mind, the word that pays back. A Jupiter year returns to you over the months the understanding you once gave. Receive the credit honestly across the year, your earlier honesty earned it.",
    Saturn: "The Six of Clubs is the card of the responsible mind, the duty you cannot set down. A Saturn year keeps a mental obligation on your shoulders across the twelve months. Carry it well through the year, being trusted with the truth is its own quiet weight.",
    Uranus: "The Six of Clubs is the card of the responsible mind, fate rearranging your thinking. A Uranus year delivers a sudden message over the months that changes the account. Let it reorder you across the year, the disruption squares something overdue.",
    Neptune: "The Six of Clubs is the card of the responsible mind, truth owed across distance. A Neptune year brings a long-due word quietly home across the twelve months. Trust the slow arrival of honesty through the year, it reaches the right ear in time."
  } },
  "7_clubs": { name: "Seven of Clubs", planets: {
    Mercury: "The Seven of Clubs is the card of the doubting mind, knowledge tested against faith. A Mercury year lets doubt argue loudly across the twelve months. Let it speak through the year, then keep faith with the deeper thing you understand.",
    Venus: "The Seven of Clubs is the card of the doubting mind, belief asked to soften. A Venus year warms the year's worry, fears eased by a gentler view. Trust the kinder reading across the months, the mind tortures itself with the harsher one for nothing.",
    Mars: "The Seven of Clubs is the card of the doubting mind, a mental fight you cannot win by force. A Mars year urges you across the twelve months to argue your way out. Stop forcing the thought through the year, the answer comes when you stop wrestling it.",
    Jupiter: "The Seven of Clubs is the card of the doubting mind, faith over worry. A Jupiter year rewards over the months the trust that anxiety called naive. Believe the better outcome across the year, and watch the dread prove small.",
    Saturn: "The Seven of Clubs is the card of the doubting mind, the long test of belief. A Saturn year sets a heavy uncertainty on you across the twelve months, a doubt that wears. Endure it without bitterness through the year, faith held under pressure is the only kind that counts.",
    Uranus: "The Seven of Clubs is the card of the doubting mind, certainty suddenly loosened. A Uranus year frees you over the months from a belief you clung to past its truth. Let it go across the year, the mind opens only when it stops defending the wall.",
    Neptune: "The Seven of Clubs is the card of the doubting mind, faith past the reach of proof. A Neptune year asks you to trust across the twelve months what you cannot quite verify. Rest in the not-knowing through the year, some truths are felt before they are shown."
  } },
  "8_clubs": { name: "Eight of Clubs", planets: {
    Mercury: "The Eight of Clubs is the card of the powerful mind, the word with force in it. A Mercury year sharpens your speech across the twelve months, language that can move and persuade. Use the power to clarify through the year, not to bludgeon.",
    Venus: "The Eight of Clubs is the card of the powerful mind, persuasion turned warm. A Venus year softens your influence over the months, a mind that wins by grace. Charm with the truth across the year, and let no one feel cornered by your cleverness.",
    Mars: "The Eight of Clubs is the card of the powerful mind, the will behind the word. A Mars year wants the thought to dominate across the twelve months. Press your point with strength through the year, and stop short of crushing the other voice.",
    Jupiter: "The Eight of Clubs is the card of the powerful mind, influence that grows. A Jupiter year widens your reach over the months, your words carrying further. Speak generously across the year, the more good you broadcast the wider it travels.",
    Saturn: "The Eight of Clubs is the card of the powerful mind, strength put to use. A Saturn year asks your sharp mind to do hard, patient work across the twelve months. Bend it to the difficult task through the year, the power is for building and not for show.",
    Uranus: "The Eight of Clubs is the card of the powerful mind, a sudden brilliance. A Uranus year lights ideas over the months that startle even you. Let them through cleanly across the year, do not grip them and do not perform them.",
    Neptune: "The Eight of Clubs is the card of the powerful mind, the word that travels far. A Neptune year sends your thought past the room across the twelve months, to minds at a distance. Aim it true through the year, what you broadcast lands further than you see."
  } },
  "9_clubs": { name: "Nine of Clubs", planets: {
    Mercury: "The Nine of Clubs is the card of the wide mind, knowledge grown large enough to give away. A Mercury year brings word across the twelve months that closes an old line of thought. Read it without clinging through the year, the ending of an idea makes room for the next.",
    Venus: "The Nine of Clubs is the card of the wide mind, understanding come full. A Venus year asks you to share what you know over the months, freely and warmly. Teach what you have learned across the year, it grows by being given.",
    Mars: "The Nine of Clubs is the card of the wide mind, the idea you must release. A Mars year demands across the twelve months that you let go of a belief past its life. Open the hand through the year, what you grip out of habit is already dead.",
    Jupiter: "The Nine of Clubs is the card of the wide mind, knowledge overflowing. A Jupiter year sends more understanding than you can keep over the months. Spend it on the many across the year, wisdom hoarded sours and shared multiplies.",
    Saturn: "The Nine of Clubs is the card of the wide mind, an idea laid to rest. A Saturn year asks you to let a long-held thought go cleanly across the twelve months. Grieve it if you must through the year, then feel the clarity the release leaves.",
    Uranus: "The Nine of Clubs is the card of the wide mind, a sudden completion of thought. A Uranus year closes a mental chapter over the months, abrupt and freeing. Let the surprise land across the year, your head is clearer than before.",
    Neptune: "The Nine of Clubs is the card of the wide mind, the knower dissolving into the known. A Neptune year softens across the twelve months the edge between your thought and the larger truth. Let the boundary blur through the year, you lose nothing by belonging to a wider understanding."
  } },
  "10_clubs": { name: "Ten of Clubs", planets: {
    Mercury: "The Ten of Clubs is the card of the teeming mind, ideas arriving in number. A Mercury year floods the twelve months, more thoughts than you can chase. Catch the strongest few across the year, you cannot ride every wave at once.",
    Venus: "The Ten of Clubs is the card of the teeming mind, learning shared in company. A Venus year makes the year social and bright with talk. Enjoy the crowd of ideas across the months, and let the warmth of being understood lift you.",
    Mars: "The Ten of Clubs is the card of the teeming mind, the drive to master it all. A Mars year sharpens ambition across the twelve months, the will to know the most and best. Push hard through the year, and pick the worthy target before the energy scatters.",
    Jupiter: "The Ten of Clubs is the card of the teeming mind, knowledge multiplied. A Jupiter year returns your learning to you many times over the months. Receive the abundance of a quick full mind across the year, and pass it on.",
    Saturn: "The Ten of Clubs is the card of the teeming mind, public knowing with a duty under it. A Saturn year ties the recognition to responsibility across the twelve months. Wear the cleverness lightly through the year, and keep faith with the truth beneath the applause.",
    Uranus: "The Ten of Clubs is the card of the teeming mind, a sudden flood of insight. A Uranus year opens the gates over the months, ideas pouring in from everywhere. Step into the rush across the year, the unexpected mass of it formed for a reason.",
    Neptune: "The Ten of Clubs is the card of the teeming mind, knowledge from afar. A Neptune year brings learning across the twelve months from sources you cannot trace. Take the wide tide of it in through the year, and let it carry your thinking outward."
  } },
  "J_clubs": { name: "Jack of Clubs", planets: {
    Mercury: "The Jack of Clubs is the card of the quick mind, the clever youth. A Mercury year races through the twelve months, wit fast and bright and a little mischievous. Use the sharpness to illuminate across the year, not merely to score the point.",
    Venus: "The Jack of Clubs is the card of the quick mind, cleverness turned charming. A Venus year warms your wit over the months, a brightness that draws people in. Delight them with it across the year, and keep the cleverness kind.",
    Mars: "The Jack of Clubs is the card of the quick mind, wit with an edge. A Mars year sharpens the tongue across the twelve months, the urge to win every exchange. Be quick and bold through the year, and do not cut someone just to prove you can.",
    Jupiter: "The Jack of Clubs is the card of the quick mind, young brilliance widening. A Jupiter year opens your cleverness onto bigger ground over the months. Aim the wit at something worthy across the year, the talent is meant for more than tricks.",
    Saturn: "The Jack of Clubs is the card of the quick mind, cleverness asked to do real work. A Saturn year sets a discipline on the bright young mind across the twelve months. Slow the wit to a craft through the year, brilliance without patience stays a trick.",
    Uranus: "The Jack of Clubs is the card of the quick mind, sudden invention. A Uranus year sparks unexpected ideas over the months, clever and strange. Catch them and run across the year, the odd thought is the original one.",
    Neptune: "The Jack of Clubs is the card of the quick mind, wit reaching for the unseen. A Neptune year turns the cleverness toward mystery over the months, the puzzle behind the obvious. Follow the strange thread through the year, the young mind senses what it cannot yet name."
  } },
  "Q_clubs": { name: "Queen of Clubs", planets: {
    Mercury: "The Queen of Clubs is the card of the knowing mind, intuition that mothers. A Mercury year sharpens that instinct into clear words across the twelve months. Say the perceptive thing gently through the year, you see more than you let on.",
    Venus: "The Queen of Clubs is the card of the knowing mind, wisdom flowing as care. A Venus year warms your insight over the months, knowledge offered as kindness. Share what you sense across the year, and let yourself be understood in return.",
    Mars: "The Queen of Clubs is the card of the knowing mind, intuition turned fierce. A Mars year asks your insight to stand its ground across the twelve months. Trust what you know and defend it through the year, without grinding anyone under the certainty.",
    Jupiter: "The Queen of Clubs is the card of the knowing mind, wisdom that widens. A Jupiter year stretches your understanding over the months to hold more than usual. Open the knowing wide across the year, there is enough insight in you to share.",
    Saturn: "The Queen of Clubs is the card of the knowing mind, the wise one leaned on. A Saturn year brings others' confusion to your steadiness across the twelve months. Hold the clear view for them through the year, and set the boundary that keeps you whole.",
    Uranus: "The Queen of Clubs is the card of the knowing mind, intuition struck sudden. A Uranus year flashes unexpected knowing through you over the months. Trust the jolts of insight across the year, they arrive ahead of the reasons for a reason.",
    Neptune: "The Queen of Clubs is the card of the knowing mind, intuition reaching far. A Neptune year deepens your sense over the months toward the unseen and distant. Trust the quiet knowing through the year, it reads what the eyes cannot."
  } },
  "K_clubs": { name: "King of Clubs", planets: {
    Mercury: "The King of Clubs is the card of the mastered mind, knowledge that rules. A Mercury year gives you the deciding word across the twelve months, the clear thought that settles a muddle. Speak from understanding through the year, and let the clarity organize the room.",
    Venus: "The King of Clubs is the card of the mastered mind, wisdom held in a sure hand. A Venus year warms your authority over the months, knowledge offered without arrogance. Lead by understanding across the year, and make others feel safe to think near you.",
    Mars: "The King of Clubs is the card of the mastered mind, intellect and command at odds. A Mars year pulls knowing and force apart across the twelve months. Rule the argument with reason through the year, win the point without conquering the person.",
    Jupiter: "The King of Clubs is the card of the mastered mind, wisdom that leads. A Jupiter year lays the weight of leadership on your judgment over the months. Decide well across the year, and let the soundness of your thinking set the standard.",
    Saturn: "The King of Clubs is the card of the mastered mind, mastery under load. A Saturn year tests your judgment across the twelve months with a hard, weighty problem. Think it through without shortcut over the year, the discipline is the whole of the mastery.",
    Uranus: "The King of Clubs is the card of the mastered mind, steadiness meeting a new idea. A Uranus year asks the master to revise over the months without losing center. Update the view across the year, hold the core, lead the change with a clear head.",
    Neptune: "The King of Clubs is the card of the mastered mind, understanding that reaches far. A Neptune year extends your judgment across the twelve months toward the unseen and the long view. Trust the wide reach of your thinking through the year, it grasps more than the visible."
  } },
  "A_diamonds": { name: "Ace of Diamonds", planets: {
    Mercury: "The Ace of Diamonds is the card of new worth, ambition's first coin. A Mercury year turns the year's wanting into plans, fresh ideas about value and money. Write the figures down across the months, the venture begins as a clear thought.",
    Venus: "The Ace of Diamonds is the card of new worth, the first reach for value. A Venus year ties the year's ambition to beauty, a desire for something lovely and worth having. Want it openly across the months, and spend on what genuinely enriches you.",
    Mars: "The Ace of Diamonds is the card of new worth, ambition newly lit. A Mars year drives the twelve months, a hunger to earn and act. Make the bold move across the year, but count the cost before you leap.",
    Jupiter: "The Ace of Diamonds is the card of new worth, the first seed of plenty. A Jupiter year is at home and widens the prospect over the months, a real chance at increase. Plant generously across the year, the ground is willing now.",
    Saturn: "The Ace of Diamonds is the card of new worth, ambition meeting limit. A Saturn year sets a wall before the venture across the twelve months, a value you cannot reach yet. Build slowly through the year, the worth that lasts is laid one disciplined stone at a time.",
    Uranus: "The Ace of Diamonds is the card of new worth, opportunity arriving unannounced. A Uranus year makes the year's chances sudden, ventures out of nowhere. Move fast on the strange openings across the months, they know what the forecast does not.",
    Neptune: "The Ace of Diamonds is the card of new worth, value sensed before it is seen. A Neptune year points the year's ambition at the distant or not yet real. Follow the hunch across the months, but keep your feet on the ground as you reach."
  } },
  "2_diamonds": { name: "Two of Diamonds", planets: {
    Mercury: "The Two of Diamonds is the card of the deal, value exchanged between two. A Mercury year works the terms across the twelve months, negotiations that turn on clear words. Say the numbers plainly through the year, the fair deal is the honest one.",
    Venus: "The Two of Diamonds is the card of the deal, a partnership in worth. A Venus year warms the year's exchanges, shared ventures that feel like trust. Strike the bargains in good faith across the months, and let both sides come away richer.",
    Mars: "The Two of Diamonds is the card of the deal, two sides at the table. A Mars year sharpens the year to a contest, haggles with heat in them. Hold your line firmly across the months, and close before the friction spoils the trade.",
    Jupiter: "The Two of Diamonds is the card of the deal, value grown by joining. A Jupiter year widens partnerships over the twelve months, shared ventures worth more than the parts. Bring others in across the year, the deal multiplies what either could do alone.",
    Saturn: "The Two of Diamonds is the card of the deal, an agreement that must be earned. A Saturn year slows the year's bargains, terms that take patience to settle. Read the fine print through the months, the deal worth having survives a careful look.",
    Uranus: "The Two of Diamonds is the card of the deal, a sudden partnership in worth. A Uranus year brings unexpected offers across the twelve months, ventures that click fast. Trust the timing across the year, the unplanned deal often pays the best.",
    Neptune: "The Two of Diamonds is the card of the deal, value traded across distance. A Neptune year carries the year's bargains far, arrangements with people away. Trust the agreements through the months, but get the terms in writing, the dream can blur."
  } },
  "3_diamonds": { name: "Three of Diamonds", planets: {
    Mercury: "The Three of Diamonds is the card of divided value, more ledgers than one mind can settle. A Mercury year scatters your accounting across the twelve months, money pulling thought several ways. Tally it on paper through the year, the worry shrinks once the figures are real.",
    Venus: "The Three of Diamonds is the card of divided value, worth pulled many ways. A Venus year makes several purchases tempting over the months, none clearly wise. Spend on what truly enriches you across the year, not on what merely glitters.",
    Mars: "The Three of Diamonds is the card of divided value, money at war with itself. A Mars year turns the strain to friction across the twelve months, a financial worry that picks a fight. Choose one priority and fund it through the year, the tension eases as you commit.",
    Jupiter: "The Three of Diamonds is the card of divided value, more opportunity than focus. A Jupiter year sends several ventures at once over the months. Back the strongest one well across the year rather than scattering across them all.",
    Saturn: "The Three of Diamonds is the card of divided value, money fear that circles. A Saturn year hardens the worry across the twelve months, the same anxious sum repeating. Face the real number squarely through the year, dread of it costs more than the figure.",
    Uranus: "The Three of Diamonds is the card of divided value, a budget split open. A Uranus year brings the unexpected cost or chance over the months. Let it reorder your figures across the year, the surprise may point at a better use.",
    Neptune: "The Three of Diamonds is the card of divided value, worth divided between here and far. A Neptune year draws your money mind toward the distant and speculative across the twelve months. Hold the ground you stand on through the year, the far prospect can wait for clearer sight."
  } },
  "4_diamonds": { name: "Four of Diamonds", planets: {
    Mercury: "The Four of Diamonds is the card of settled value, worth on firm ground. A Mercury year brings word across the twelve months that confirms your accounts. Take the certainty in through the year, your footing is sounder than you feared.",
    Venus: "The Four of Diamonds is the card of settled value, the comfort of enough. A Venus year makes the year's security pleasant, a steady worth that feels like ease. Enjoy what you have built across the months, and stop straining for more than you need.",
    Mars: "The Four of Diamonds is the card of settled value, a holding kept firm. A Mars year sends challenges to it across the twelve months, things testing your security. Defend what is yours calmly through the year, without turning the guarding into greed.",
    Jupiter: "The Four of Diamonds is the card of settled value, sound footing. A Jupiter year widens it over the months, your stable worth stretching to hold more. Build on the firm base across the year, it will carry the added weight.",
    Saturn: "The Four of Diamonds is the card of settled value, the foundation of worth. A Saturn year tests that base across the twelve months, pressing on what you have saved. What is solid will stand the year, so let the rest be examined without panic.",
    Uranus: "The Four of Diamonds is the card of settled value, a fixed holding. A Uranus year shakes it over the months, change reaching into your secure place. Let the structure flex across the year, a wealth that cannot move is already at risk.",
    Neptune: "The Four of Diamonds is the card of settled value, worth at rest. A Neptune year softens its edges across the twelve months, security blurring toward the uncertain. Hold what you have lightly through the year, true safety was never only the figure."
  } },
  "5_diamonds": { name: "Five of Diamonds", planets: {
    Mercury: "The Five of Diamonds is the card of restless value, worth that wants to move. A Mercury year speeds the schemes across the twelve months, money ideas darting one to the next. Let them run through the year, then pin down the single plan worth acting on.",
    Venus: "The Five of Diamonds is the card of restless value, the itch for a new venture. A Venus year makes the steady thing feel dull over the months and the new deal shine. Chase the fresh prospect across the year if you must, without abandoning a sound thing half-done.",
    Mars: "The Five of Diamonds is the card of restless value, money that wants out. A Mars year charges the restlessness across the twelve months, an urge to spend, move, or risk. Aim the drive at one real opportunity through the year and put it to work.",
    Jupiter: "The Five of Diamonds is the card of restless value, the field widening. A Jupiter year opens new ground over the months, more ways to earn than before. Range generously across the year, there is more here than you risk by moving.",
    Saturn: "The Five of Diamonds is the card of restless value, the wish to bolt from the budget. A Saturn year sets the steady duty before you across the twelve months. Stay with the boring discipline through the year, it is building exactly what the restlessness wants.",
    Uranus: "The Five of Diamonds is the card of restless value, the urge to overturn the plan. A Uranus year disrupts your finances across the twelve months with something new. Let it shake things loose across the year, the stale arrangement was due to change.",
    Neptune: "The Five of Diamonds is the card of restless value, worth drifting toward the far. A Neptune year fills the months with dreams of distant gain. Let the daydream run through the year, then ask what real need is underneath the wanting."
  } },
  "6_diamonds": { name: "Six of Diamonds", planets: {
    Mercury: "The Six of Diamonds is the card of the fair exchange, value that balances its books. A Mercury year circles money matters back for settling across the twelve months. Square the accounts in plain figures through the year, fairness is the whole of what is asked.",
    Venus: "The Six of Diamonds is the card of the fair exchange, worth returned to its level. A Venus year evens the books over the months, a chance to make a money matter right. Pay what you owe gladly across the year, and let the balance restore goodwill.",
    Mars: "The Six of Diamonds is the card of the fair exchange, a debt pressing to be paid. A Mars year pushes the reckoning across the twelve months. Meet it with steadiness through the year rather than resentment, and the account comes clear.",
    Jupiter: "The Six of Diamonds is the card of the fair exchange, value paid back. A Jupiter year returns over the months what you once gave or invested, enriched. Receive it without suspicion across the year, an honest exchange has come full circle.",
    Saturn: "The Six of Diamonds is the card of the fair exchange, the obligation you must honor. A Saturn year keeps a financial duty on you across the twelve months. Pay it in full and on time through the year, your good name is the real asset.",
    Uranus: "The Six of Diamonds is the card of the fair exchange, accounts squared by surprise. A Uranus year settles money matters abruptly over the months, in or out of your favor. Accept the rebalancing across the year, it is correcting something overdue.",
    Neptune: "The Six of Diamonds is the card of the fair exchange, worth owed across distance. A Neptune year brings long-due payments quietly home across the twelve months. Trust the slow fairness of the year, what is owed finds its way back."
  } },
  "7_diamonds": { name: "Seven of Diamonds", planets: {
    Mercury: "The Seven of Diamonds is the card of tested value, worth held against worry. A Mercury year lets money fear talk loudly across the twelve months. Hear it out through the year, then trust the plan you made when your head was clear.",
    Venus: "The Seven of Diamonds is the card of tested value, security asked to soften its grip. A Venus year eases the year's money worry with a gentler view. Loosen the clutch across the months, what you hold too tightly brings no real peace.",
    Mars: "The Seven of Diamonds is the card of tested value, a financial fight you cannot force. A Mars year urges you to grab and grasp across the twelve months. Stop chasing it through the year, the worth you need arrives when you stop strangling it.",
    Jupiter: "The Seven of Diamonds is the card of tested value, faith over money fear. A Jupiter year rewards over the months the trust that anxiety called reckless. Believe in enough across the year, and the lack proves smaller than it threatened.",
    Saturn: "The Seven of Diamonds is the card of tested value, the long discipline of worth. A Saturn year sets a financial strain on you across the twelve months, a lean stretch to endure. Bear it without bitterness through the year, the tight season passes.",
    Uranus: "The Seven of Diamonds is the card of tested value, a grip suddenly loosened. A Uranus year frees you over the months from a holding you clutched past reason. Let it go across the year, what you release on purpose makes room for better.",
    Neptune: "The Seven of Diamonds is the card of tested value, worth beyond what you can count. A Neptune year asks you to trust across the twelve months what the ledger cannot show. Rest a little in the not-knowing through the year, real security is not only a number."
  } },
  "8_diamonds": { name: "Eight of Diamonds", planets: {
    Mercury: "The Eight of Diamonds is the card of powerful value, worth with weight behind it. A Mercury year sharpens your money sense across the twelve months, a clear eye for the sound deal. Use the shrewdness to build through the year, not merely to take.",
    Venus: "The Eight of Diamonds is the card of powerful value, earning turned graceful. A Venus year warms your power over the months, prosperity that comes through goodwill. Earn by serving well across the year, and let the wealth keep its warmth.",
    Mars: "The Eight of Diamonds is the card of powerful value, the drive behind the dollar. A Mars year wants the earning to dominate across the twelve months. Work hard for it through the year, and do not let the getting harden you.",
    Jupiter: "The Eight of Diamonds is the card of powerful value, prosperity that grows. A Jupiter year widens your earning over the months, returns stretching beyond the usual. Put the surplus to work across the year, money that moves makes more.",
    Saturn: "The Eight of Diamonds is the card of powerful value, strength set to the long task. A Saturn year asks your earning power to do patient work across the twelve months. Bend it to the durable thing through the year, the worth built slowly is the worth that holds.",
    Uranus: "The Eight of Diamonds is the card of powerful value, a sudden turn of fortune. A Uranus year jolts your finances over the months, gains or shifts you did not expect. Let it move through cleanly across the year, ride the change without gripping.",
    Neptune: "The Eight of Diamonds is the card of powerful value, worth that reaches far. A Neptune year sends your earning past the room across the twelve months, into ventures at a distance. Aim it true through the year, and keep clear sight on what you cannot watch."
  } },
  "9_diamonds": { name: "Nine of Diamonds", planets: {
    Mercury: "The Nine of Diamonds is the card of wide value, wealth grown large enough to give away. A Mercury year brings word across the twelve months that closes a financial chapter. Read it without clinging through the year, the ending of one venture funds the next.",
    Venus: "The Nine of Diamonds is the card of wide value, worth come full. A Venus year asks the year's abundance to be shared, not hoarded. Give from your plenty across the months, generosity is wealth that finally knows its purpose.",
    Mars: "The Nine of Diamonds is the card of wide value, the holding you must release. A Mars year demands across the twelve months that you let go of money or a venture past its life. Open the hand through the year, what you grip from fear is already slipping.",
    Jupiter: "The Nine of Diamonds is the card of wide value, abundance overflowing. A Jupiter year sends more than you can keep over the months. Spend it on the many across the year, wealth held too close goes stale and shared comes back.",
    Saturn: "The Nine of Diamonds is the card of wide value, a loss to be met with grace. A Saturn year asks you to let a holding go cleanly across the twelve months. Accept it without bitterness through the year, and notice the freedom the lighter ledger brings.",
    Uranus: "The Nine of Diamonds is the card of wide value, a sudden settling of accounts. A Uranus year closes a money chapter abruptly over the months. Let the surprise land across the year, your position is clearer than before.",
    Neptune: "The Nine of Diamonds is the card of wide value, worth dissolving into a larger good. A Neptune year softens your grip on having across the twelve months. Loosen it through the year, you lose nothing real by letting your wealth serve more than yourself."
  } },
  "10_diamonds": { name: "Ten of Diamonds", planets: {
    Mercury: "The Ten of Diamonds is the card of abundant value, the trader who knows worth and will not sell it cheap. A Mercury year turns that knowing into shrewd dealing across the twelve months, sharpened by a clear tongue. Name your prices plainly through the year, and let the figures speak.",
    Venus: "The Ten of Diamonds is the card of abundant value, the trader who knows worth. A Venus year warms the year's prosperity, wealth that flows through goodwill and good taste. Spend on what is genuinely fine across the months, and let your abundance be gracious.",
    Mars: "The Ten of Diamonds is the card of abundant value, the trader who refuses to sell cheap. A Mars year charges the ambition across the twelve months, a hunger to earn big and win the trade. Drive hard for the worthy deals through the year, and stop short of greed.",
    Jupiter: "The Ten of Diamonds is the card of abundant value, worth in full measure. A Jupiter year is doubly at home, prosperity widening on every side over the months. Receive the increase openly across the year, and let the plenty pass through your hands to others.",
    Saturn: "The Ten of Diamonds is the card of abundant value, the trader who knows worth and refuses to sell it cheap. A Saturn year sharpens that knowing into structure, twelve months that reward the steady ledger over the lucky strike, the thing built to last over the thing that merely glitters. Name your price, honor your limits, and let what you build across the year carry real weight.",
    Uranus: "The Ten of Diamonds is the card of abundant value, fortune in full. A Uranus year brings sudden turns across the twelve months, windfalls or shifts in worth. Move quickly and lightly across the year, ride the changes without clutching.",
    Neptune: "The Ten of Diamonds is the card of abundant value, worth that reaches far. A Neptune year extends your prosperity over the months toward the distant and unseen. Trust the wide reach through the year, and keep clear eyes on ventures you cannot directly watch."
  } },
  "J_diamonds": { name: "Jack of Diamonds", planets: {
    Mercury: "The Jack of Diamonds is the card of the young trader, sharp and quick with worth. A Mercury year races through the twelve months, a clever eye for the deal and the angle. Use the sharpness to make honest profit across the year, not a quick trick.",
    Venus: "The Jack of Diamonds is the card of the young trader, charm that sells. A Venus year warms your dealing over the months, a likeable knack for value. Win the trades by being genuinely liked across the year, and keep the charm honest.",
    Mars: "The Jack of Diamonds is the card of the young trader, hungry and bold. A Mars year fires the ambition across the twelve months, an urge to grab the gain. Be quick and daring through the year, and do not cut a corner you will pay for later.",
    Jupiter: "The Jack of Diamonds is the card of the young trader, opportunity widening. A Jupiter year opens the field over the months for a bright young venture. Aim higher than a fast buck across the year, the talent is built for more than small wins.",
    Saturn: "The Jack of Diamonds is the card of the young trader, cleverness asked to mature. A Saturn year disciplines the quick deal across the twelve months. Slow the hustle into real craft through the year, sharpness without patience stays a gamble.",
    Uranus: "The Jack of Diamonds is the card of the young trader, a sudden clever opening. A Uranus year sparks unexpected ventures over the months, odd and promising. Seize the strange opportunities across the year, the unusual deal is often the live one.",
    Neptune: "The Jack of Diamonds is the card of the young trader, an eye on the far horizon. A Neptune year turns the dealing toward the distant and speculative over the months. Chase the vision across the year if you like, but verify before you stake real coin."
  } },
  "Q_diamonds": { name: "Queen of Diamonds", planets: {
    Mercury: "The Queen of Diamonds is the card of the providing hand, worth that nurtures. A Mercury year sharpens your practical sense across the twelve months, a clear head for what others need. Arrange the resources plainly through the year, your provision is felt in the details.",
    Venus: "The Queen of Diamonds is the card of the providing hand, value given as care. A Venus year warms your generosity over the months, abundance shared with grace. Provide freely across the year, and let yourself be provided for in turn.",
    Mars: "The Queen of Diamonds is the card of the providing hand, generosity turned fierce. A Mars year asks you to fight for someone's security across the twelve months. Defend their share with strength through the year, and keep the fierceness clean of control.",
    Jupiter: "The Queen of Diamonds is the card of the providing hand, plenty that widens. A Jupiter year stretches your means over the months to hold more than usual. Open the purse with an even hand across the year, there is enough to go around.",
    Saturn: "The Queen of Diamonds is the card of the providing hand, the one others rely on. A Saturn year lays material need against your steadiness across the twelve months. Provide reliably through the year, and set the limit that keeps your own well full.",
    Uranus: "The Queen of Diamonds is the card of the providing hand, care called to improvise. A Uranus year brings sudden needs over the months that no budget planned for. Meet them freshly across the year, provision is a living act, not a fixed sum.",
    Neptune: "The Queen of Diamonds is the card of the providing hand, giving that reaches far. A Neptune year sends your generosity across the twelve months toward the distant and unseen in need. Give anyway through the year, real provision crosses the distance and lands."
  } },
  "K_diamonds": { name: "King of Diamonds", planets: {
    Mercury: "The King of Diamonds is the card of mastered value, worth that rules. A Mercury year gives you the deciding word on money across the twelve months. Speak from clear figures through the year, and let the soundness of the call settle the room.",
    Venus: "The King of Diamonds is the card of mastered value, wealth held in a sure hand. A Venus year warms your authority over the months, prosperity led with grace. Provide and decide warmly across the year, and let your steadiness be the security others rest on.",
    Mars: "The King of Diamonds is the card of mastered value, command and worth at odds. A Mars year pulls money and force apart across the twelve months. Rule the ventures with judgment through the year, win the deals without crushing the other side.",
    Jupiter: "The King of Diamonds is the card of mastered value, prosperity that leads. A Jupiter year lays the weight of leadership on your means over the months. Steward it well across the year, and let the abundance you handle raise the standard.",
    Saturn: "The King of Diamonds is the card of mastered value, mastery under load. A Saturn year tests your judgment across the twelve months with a heavy financial weight. Decide without shortcut through the year, the patient call is the masterful one.",
    Uranus: "The King of Diamonds is the card of mastered value, steadiness meeting a market shift. A Uranus year asks the master to adapt over the months without losing center. Adjust the plan across the year, hold the principle, lead the change with a cool head.",
    Neptune: "The King of Diamonds is the card of mastered value, worth that reaches far. A Neptune year extends your command across the twelve months over distant and unseen ventures. Trust the long reach of your judgment through the year, and keep clear sight on what you cannot watch."
  } },
  "A_spades": { name: "Ace of Spades", planets: {
    Mercury: "The Ace of Spades is the card of the seeking will, ambition for the deepest thing. A Mercury year turns that hunger into questions across the twelve months, the mind reaching for what is hidden. Ask the hard questions through the year, the answer you avoid is the one you need.",
    Venus: "The Ace of Spades is the card of the seeking will, the reach for the profound. A Venus year softens the search over the months, a love of the deep and the true. Pursue it gently across the year, the most serious things open to a warm approach.",
    Mars: "The Ace of Spades is the card of the seeking will, ambition newly fierce. A Mars year puts force behind the work across the twelve months, a drive to begin the hard thing. Start it through the year, the will is lit and the labor is yours to claim.",
    Jupiter: "The Ace of Spades is the card of the seeking will, a deep aim widening. A Jupiter year blesses the undertaking over the months, the great work given room to grow. Begin generously across the year, the ground favors serious effort now.",
    Saturn: "The Ace of Spades is the card of the seeking will, ambition meeting the long road. A Saturn year is at home and sets the discipline across the twelve months. Commit for the long haul through the year, the deepest thing is built by patient labor and no shortcut.",
    Uranus: "The Ace of Spades is the card of the seeking will, the call arriving sudden. A Uranus year opens a hidden door over the months, a transformation you did not see coming. Walk through it across the year, the strange summons knows where it leads.",
    Neptune: "The Ace of Spades is the card of the seeking will, the reach toward mystery itself. A Neptune year turns the year's ambition to the unseen, the spirit behind the work. Follow the depth through the months, this card belongs to the things beyond sight."
  } },
  "2_spades": { name: "Two of Spades", planets: {
    Mercury: "The Two of Spades is the card of joined labor, two at one task. A Mercury year coordinates the work across the twelve months, effort that turns on clear instruction. Say who does what plainly through the year, the shared job runs on good communication.",
    Venus: "The Two of Spades is the card of joined labor, work shared in goodwill. A Venus year warms the year's partnership, tasks lightened by a willing companion. Work side by side in trust across the months, and the labor itself becomes a bond.",
    Mars: "The Two of Spades is the card of joined labor, two wills on one task. A Mars year strikes friction across the twelve months, clashes over how the work gets done. Pull together rather than against through the year, and let the shared goal settle the method.",
    Jupiter: "The Two of Spades is the card of joined labor, effort doubled by joining. A Jupiter year widens the work over the months, more hands making a larger thing possible. Bring others in across the year, the task grows lighter as the circle grows.",
    Saturn: "The Two of Spades is the card of joined labor, a partnership that must be earned. A Saturn year tests the working bond across the twelve months with strain or delay. Show up for the dull stretch through the year, the alliance that survives the grind is the real one.",
    Uranus: "The Two of Spades is the card of joined labor, a sudden working pair. A Uranus year throws you together over the months with an unlikely collaborator. Trust the odd match across the year, the unplanned partnership often does the best work.",
    Neptune: "The Two of Spades is the card of joined labor, work joined across distance. A Neptune year links the year's effort with someone far. Trust the shared task through the months, the bond of common work holds over any gap."
  } },
  "3_spades": { name: "Three of Spades", planets: {
    Mercury: "The Three of Spades is the card of divided labor, more work than one will can settle. A Mercury year scatters the tasks across the twelve months, effort pulled too many directions. List them and rank them through the year, the overwhelm shrinks once the work is on paper.",
    Venus: "The Three of Spades is the card of divided labor, effort pulled many ways. A Venus year asks you to choose the work that nourishes over the months over the work that merely fills time. Tend the task that matters across the year, and let a lesser one wait.",
    Mars: "The Three of Spades is the card of divided labor, tasks at war for your hands. A Mars year turns the overload to friction across the twelve months, a strain that frays the temper. Pick one job and finish it through the year, the pressure eases as something gets done.",
    Jupiter: "The Three of Spades is the card of divided labor, more to do than focus allows. A Jupiter year piles on opportunity over the months, all of it worthwhile. Do one well rather than three poorly across the year, the surplus is a luxury only if you choose.",
    Saturn: "The Three of Spades is the card of divided labor, worry that wears at the body. A Saturn year hardens the strain across the twelve months into a knot of work-fear or fatigue. Name the real load plainly through the year, and rest before the worry does the damage.",
    Uranus: "The Three of Spades is the card of divided labor, a plan split open. A Uranus year drops the unexpected task or setback over the months. Let it reorder your effort across the year, the disruption may clear room for the work that counts.",
    Neptune: "The Three of Spades is the card of divided labor, effort divided between here and far. A Neptune year pulls your attention from the task toward the distant and dreamed across the twelve months. Bring yourself back to the work in front of you through the year, the far thing can wait."
  } },
  "4_spades": { name: "Four of Spades", planets: {
    Mercury: "The Four of Spades is the card of settled labor, rest the work has earned. A Mercury year brings word across the twelve months that a task is truly done. Take it in through the year, and let yourself actually stop.",
    Venus: "The Four of Spades is the card of settled labor, the ease after effort. A Venus year makes the year's rest sweet, a peace your work has paid for. Enjoy the quiet across the months, you are allowed to set the tools down.",
    Mars: "The Four of Spades is the card of settled labor, a hard-won stability. A Mars year sends things to disturb the rest across the twelve months. Guard your recovery through the year, and do not let restlessness drag you back to work too soon.",
    Jupiter: "The Four of Spades is the card of settled labor, secure ground beneath the work. A Jupiter year widens the stability over the months, your foundation holding more than before. Build on the solid base across the year, the rest has made you ready.",
    Saturn: "The Four of Spades is the card of settled labor, the foundation effort built. A Saturn year tests that base across the twelve months, pressing on what you established. What was built well will stand the year, so trust it and shore up the rest.",
    Uranus: "The Four of Spades is the card of settled labor, a fixed routine. A Uranus year shakes the steady work over the months, change reaching into the settled place. Let the method flex across the year, a practice that cannot adapt is already failing.",
    Neptune: "The Four of Spades is the card of settled labor, rest that runs deep. A Neptune year softens the edges of effort across the twelve months, the body asking for true stillness. Give it the deep rest through the year, restoration is its own quiet work."
  } },
  "5_spades": { name: "Five of Spades", planets: {
    Mercury: "The Five of Spades is the card of restless labor, work that wants new ground. A Mercury year speeds the urge to change tack across the twelve months, plans for different work. Let the ideas move through the year, then commit to one before it all scatters.",
    Venus: "The Five of Spades is the card of restless labor, the itch to leave the work. A Venus year makes the current task feel stale over the months and a new one shine. Move on across the year if you must, without walking out on something nearly finished.",
    Mars: "The Five of Spades is the card of restless labor, effort that wants out. A Mars year charges the restlessness across the twelve months, a need to break from the grind. Spend it in real change through the year, then return to the work renewed.",
    Jupiter: "The Five of Spades is the card of restless labor, the field widening. A Jupiter year opens new work over the months, more directions than before. Range generously across the year, there is more to gain than the comfort you would keep.",
    Saturn: "The Five of Spades is the card of restless labor, the wish to quit the task. A Saturn year sets the unfinished duty before you across the twelve months. Stay with it through the year, the discipline you resist is the one that finishes the thing.",
    Uranus: "The Five of Spades is the card of restless labor, the urge to overturn the work. A Uranus year disrupts the routine across the twelve months with something new. Let it break the rut across the year, the stale way of working was overdue to go.",
    Neptune: "The Five of Spades is the card of restless labor, effort drifting toward escape. A Neptune year fills the months with longing to be anywhere but the task. Let the daydream pass through the year, then ask what the work is really lacking."
  } },
  "6_spades": { name: "Six of Spades", planets: {
    Mercury: "The Six of Spades is the card of the carried burden, labor that must be borne. A Mercury year circles a duty back to you across the twelve months, a task you cannot delegate. Take it up plainly through the year, doing the next right thing without dramatizing the weight.",
    Venus: "The Six of Spades is the card of the carried burden, duty met with grace. A Venus year eases the year's load, a heavy task softened by good company. Carry it gently across the months, the burden shared is half a burden.",
    Mars: "The Six of Spades is the card of the carried burden, the work pressing to be done. A Mars year pushes the obligation across the twelve months. Meet it with steady strength through the year rather than complaint, and the weight moves.",
    Jupiter: "The Six of Spades is the card of the carried burden, effort that pays back. A Jupiter year returns over the months the fruit of work you once did. Receive it without protest across the year, the labor is coming full circle.",
    Saturn: "The Six of Spades is the card of the carried burden, the duty you cannot set down. A Saturn year is heavy on this card across the twelve months, a responsibility fixed to your shoulders. Carry it well through the year, this steady weight is what makes you trusted.",
    Uranus: "The Six of Spades is the card of the carried burden, fate rearranging the load. A Uranus year shifts your obligations suddenly over the months. Let the burden be redistributed across the year, the change corrects something long out of balance.",
    Neptune: "The Six of Spades is the card of the carried burden, a duty owed across distance. A Neptune year brings a long-standing obligation quietly due across the twelve months. Honor it through the year, the slow accounting of work finds its way home."
  } },
  "7_spades": { name: "Seven of Spades", planets: {
    Mercury: "The Seven of Spades is the card of the tested will, the soul's hard labor. A Mercury year lets discouragement talk loudly across the twelve months, every effort doubted. Hear it out through the year, then keep working from what you know.",
    Venus: "The Seven of Spades is the card of the tested will, hardship asked to soften. A Venus year brings a gentler strength over the months, the labor eased by kindness toward yourself. Be tender with your struggle across the year, harshness only adds to the weight.",
    Mars: "The Seven of Spades is the card of the tested will, a fight you cannot win by force. A Mars year urges you to push harder across the twelve months against an immovable thing. Stop forcing it through the year, conserve the strength, and let the obstacle teach its patience.",
    Jupiter: "The Seven of Spades is the card of the tested will, faith over despair. A Jupiter year rewards over the months the trust that exhaustion called foolish. Hold on across the year, and the wall proves lower than it looked from your knees.",
    Saturn: "The Seven of Spades is the card of the tested will, the long ordeal. A Saturn year sets real endurance on you across the twelve months, a hardship of work or health to bear. Bear it without bitterness through the year, and pace yourself, it is shorter than it feels.",
    Uranus: "The Seven of Spades is the card of the tested will, a sudden release from struggle. A Uranus year loosens the grip over the months on a hardship you held too long. Let it go across the year, the relief you did not plan for is real.",
    Neptune: "The Seven of Spades is the card of the tested will, faith past the reach of proof. A Neptune year asks you to trust across the twelve months a labor whose meaning you cannot yet see. Keep at it in the dark through the year, you are held even where the way is unclear."
  } },
  "8_spades": { name: "Eight of Spades", planets: {
    Mercury: "The Eight of Spades is the card of the powerful will, labor with force in it. A Mercury year sharpens your focus across the twelve months, a mind that can drive a task to its end. Use the power deliberately through the year, aimed at the work that matters most.",
    Venus: "The Eight of Spades is the card of the powerful will, strength turned gentle. A Venus year warms your force over the months, power that serves rather than dominates. Apply it with care across the year, the strongest will is the one that knows restraint.",
    Mars: "The Eight of Spades is the card of the powerful will, raw drive. A Mars year is fierce on this card across the twelve months, strength that wants to overpower the task and everyone near it. Push hard through the year, and watch the force does not become a hammer for its own sake.",
    Jupiter: "The Eight of Spades is the card of the powerful will, strength that grows. A Jupiter year widens your capacity over the months, more able to do and endure. Spend the power generously across the year, used well it expands.",
    Saturn: "The Eight of Spades is the card of the powerful will, force set to the long task. A Saturn year asks your strength to do patient, grinding work across the twelve months. Bend it to the durable thing through the year, the will proves itself in endurance, not in show.",
    Uranus: "The Eight of Spades is the card of the powerful will, a sudden surge of strength. A Uranus year jolts your drive over the months, an energy that arrives from nowhere. Let it move through cleanly across the year, ride the surge without letting it ride you.",
    Neptune: "The Eight of Spades is the card of the powerful will, strength that reaches far. A Neptune year sends your influence past the room across the twelve months, your effort felt at a distance. Aim it true through the year, the force you exert travels further than you see."
  } },
  "9_spades": { name: "Nine of Spades", planets: {
    Mercury: "The Nine of Spades is the card of the great ending, the will that lets go. A Mercury year brings word across the twelve months that something is finished. Read it without flinching through the year, an honest ending is the start of the next true thing.",
    Venus: "The Nine of Spades is the card of the great ending, release made gentle. A Venus year softens the year's loss, a goodbye that need not be bitter. Let it go with love across the months, what ends in grace leaves room for grace to come.",
    Mars: "The Nine of Spades is the card of the great ending, the grip you must finally break. A Mars year demands across the twelve months that you release what is already gone. Open the hand through the year, fighting the ending only bloodies you against the inevitable.",
    Jupiter: "The Nine of Spades is the card of the great ending, the wide clearing. A Jupiter year widens the release over the months, a letting-go that opens real space. Give it up generously across the year, what you free makes room for something larger.",
    Saturn: "The Nine of Spades is the card of the great ending, the loss to be met with dignity. A Saturn year brings the final settling across the twelve months, the close of a long matter. Grieve it cleanly through the year, accept what is finished, and let the weight lift.",
    Uranus: "The Nine of Spades is the card of the great ending, an abrupt completion. A Uranus year cuts the cord suddenly over the months, an ending you did not choose. Let the shock pass through across the year, the clearing it leaves is real and yours.",
    Neptune: "The Nine of Spades is the card of the great ending, the self dissolving into something larger. A Neptune year softens across the twelve months the boundary between holding on and letting go. Release it into the deep through the year, nothing true is ever actually lost."
  } },
  "10_spades": { name: "Ten of Spades", planets: {
    Mercury: "The Ten of Spades is the card of teeming labor, work arriving in number. A Mercury year floods you with tasks across the twelve months, more than one mind can track. Write them down and take them in order through the year, the mountain moves one step at a time.",
    Venus: "The Ten of Spades is the card of teeming labor, effort shared in company. A Venus year makes the heavy work lighter over the months through good company. Lean on the team across the year, and let the warmth of doing it together carry you.",
    Mars: "The Ten of Spades is the card of teeming labor, the drive to achieve it all. A Mars year sharpens ambition across the twelve months, the will to finish the whole great pile. Push hard through the year, and choose the vital tasks before the energy spreads thin.",
    Jupiter: "The Ten of Spades is the card of teeming labor, work rewarded in full. A Jupiter year returns your effort to you many times over the months. Receive the achievement openly across the year, and share the credit with the hands that helped.",
    Saturn: "The Ten of Spades is the card of teeming labor, accomplishment with a duty under it. A Saturn year ties the success to responsibility across the twelve months. Carry the load without grinding yourself down through the year, and pace the great work for the long haul.",
    Uranus: "The Ten of Spades is the card of teeming labor, a sudden surge of work. A Uranus year opens the floodgates over the months, demands pouring in. Step into the rush across the year, the great push formed around you for a reason.",
    Neptune: "The Ten of Spades is the card of teeming labor, work whose end you cannot yet see. A Neptune year blurs the finish line across the twelve months, the task feeling vast and vague. Trust the effort through the year, do the next piece, the far end arrives as you walk."
  } },
  "J_spades": { name: "Jack of Spades", planets: {
    Mercury: "The Jack of Spades is the card of the apprentice will, the youth at hard work. A Mercury year quickens a clever approach to the labor across the twelve months. Use the wit to work smarter through the year, then put in the hours it still demands.",
    Venus: "The Jack of Spades is the card of the apprentice will, effort offered with heart. A Venus year warms the young worker over the months, a labor done for love of the craft. Give yourself to it gladly across the year, and keep a little ease for yourself.",
    Mars: "The Jack of Spades is the card of the apprentice will, eager and untested strength. A Mars year fires the drive across the twelve months, the urge to prove yourself through work. Throw yourself in through the year, and watch the boldness does not outrun the skill.",
    Jupiter: "The Jack of Spades is the card of the apprentice will, young effort widening. A Jupiter year opens the craft over the months onto bigger ground. Aim past the small task across the year, the talent is meant to grow into real mastery.",
    Saturn: "The Jack of Spades is the card of the apprentice will, eagerness asked to mature. A Saturn year sets the long discipline on you across the twelve months. Trade the quick result for true craft through the year, the apprentice becomes the master only through patience.",
    Uranus: "The Jack of Spades is the card of the apprentice will, a sudden new method. A Uranus year sparks an unexpected way of working over the months, odd and effective. Try the strange approach across the year, the original method is often the apprentice's gift.",
    Neptune: "The Jack of Spades is the card of the apprentice will, work reaching toward the unseen. A Neptune year turns the labor over the months toward the subtle, the artful, the spiritual. Follow the deeper pull through the year, the young hand senses a craft it cannot yet name."
  } },
  "Q_spades": { name: "Queen of Spades", planets: {
    Mercury: "The Queen of Spades is the card of laboring wisdom, the one who has done the work. A Mercury year sharpens your hard-won knowing into clear words across the twelve months. Say the seasoned thing plainly through the year, you have earned the right to be heard.",
    Venus: "The Queen of Spades is the card of laboring wisdom, strength carried with grace. A Venus year warms your competence over the months, mastery offered as care. Help with your skill across the year, and let your steadiness reassure the ones who lean in.",
    Mars: "The Queen of Spades is the card of laboring wisdom, hard knowing turned fierce. A Mars year asks your experience to stand firm across the twelve months. Defend what your labor taught you through the year, and wield the authority without contempt for the green.",
    Jupiter: "The Queen of Spades is the card of laboring wisdom, mastery that widens. A Jupiter year stretches your capability over the months to carry more than usual. Take on the larger work across the year, your seasoned hands are equal to it.",
    Saturn: "The Queen of Spades is the card of laboring wisdom, the strong one leaned on. A Saturn year lays real weight on your competence across the twelve months. Carry it steadily through the year, and set the boundary that keeps even the capable from breaking.",
    Uranus: "The Queen of Spades is the card of laboring wisdom, skill asked to improvise. A Uranus year brings problems over the months that your old methods do not fit. Adapt on the spot across the year, true mastery shows most in the unplanned moment.",
    Neptune: "The Queen of Spades is the card of laboring wisdom, knowing that reaches the unseen. A Neptune year deepens your insight over the months toward the subtle and spiritual. Trust the quiet wisdom your work has earned through the year, it reads what others miss."
  } },
  "K_spades": { name: "King of Spades", planets: {
    Mercury: "The King of Spades is the card of mastered will, wisdom that rules. A Mercury year gives you the decisive word across the twelve months, the hard-earned judgment that cuts through. Speak from experience through the year, and let the authority of real knowing settle the matter.",
    Venus: "The King of Spades is the card of mastered will, power held with grace. A Venus year warms your command over the months, mastery that leads without cruelty. Rule the work warmly across the year, and let your steadiness be the ground others build on.",
    Mars: "The King of Spades is the card of mastered will, command and force at odds. A Mars year pulls strength and wisdom apart across the twelve months. Govern the hard task with judgment through the year, drive the work without becoming a tyrant over it.",
    Jupiter: "The King of Spades is the card of mastered will, mastery that leads. A Jupiter year lays the weight of leadership on your seasoned judgment over the months. Decide well across the year, and let the depth of your experience raise everyone around you.",
    Saturn: "The King of Spades is the card of mastered will, mastery under full load. A Saturn year is at home on this highest card across the twelve months, testing your strength with real weight. Carry it without shortcut through the year, the discipline is the whole of the kingship.",
    Uranus: "The King of Spades is the card of mastered will, steadiness meeting upheaval. A Uranus year asks the master to adapt across the twelve months without losing center. Change the method through the year, hold the principle, and lead the disruption with a calm, sure hand.",
    Neptune: "The King of Spades is the card of mastered will, authority that reaches the unseen. A Neptune year extends your wisdom over the months toward the deepest and most distant things. Trust the long reach of your knowing through the year, it governs more than the visible world."
  } }
};
